#
# Automatically generated make config: don't edit
#

#
# Library Configuration
#

#
# Force build (Normally built when required)
#
# CONFIG_LIB_LIBGMP_FORCE is not set
CONFIG_LIB_LIBPTHREAD_FORCE=y
CONFIG_LIB_LIBNVRAM_FORCE=y
# CONFIG_LIB_LIBNTFS3G_FORCE is not set
# CONFIG_LIB_LIBBT_FORCE is not set
# CONFIG_LIB_READLINE_FORCE is not set
# CONFIG_LIB_NL_FORCE is not set
# CONFIG_LIB_LIBPCAP_FORCE is not set
# CONFIG_LIB_LIBEVENT_FORCE is not set
# CONFIG_LIB_NCURSE_FORCE is not set
CONFIG_LIB_FLEX_FORCE=y
# CONFIG_LIB_LIBUPNP_FORCE is not set
# CONFIG_LIB_LIBUPNP166_DMS_FORCE is not set
# CONFIG_LIB_LIBDLNA_FORCE is not set
# CONFIG_LIB_LIBFFMPEG_FORCE is not set
# CONFIG_LIB_LIBGDBM_FORCE is not set
# CONFIG_LIB_LIBID3TAG_FORCE is not set
# CONFIG_LIB_LIBSQLITE3_FORCE is not set
# CONFIG_LIB_LIBEXIF_FORCE is not set
# CONFIG_LIB_LIBOGG_FORCE is not set
# CONFIG_LIB_LIBVORBIS_FORCE is not set
# CONFIG_LIB_LIBFLAC_FORCE is not set
# CONFIG_LIB_LIBJPEG_FORCE is not set
# CONFIG_LIB_LIBDB_FORCE is not set
# CONFIG_LIB_USB0112_FORCE is not set
CONFIG_LIB_USB100_FORCE=y
CONFIG_LIB_PCRE_FORCE=y
# CONFIG_LIB_VSTR_FORCE is not set
CONFIG_LIB_ZLIB_FORCE=y
# CONFIG_LIB_LZO_FORCE is not set
# CONFIG_LIB_E2FSPROGS_FORCE is not set
# CONFIG_LIB_LIBSTDC_PLUS_FORCE is not set
# CONFIG_USER_HELLO_WORLD is not set
CONFIG_LIB_LIBPTHREAD_FORCE=y

#
# MTD utils
#
# CONFIG_USER_MTDUTILS is not set
# CONFIG_USER_MTDUTILS_DOCFDISK is not set
# CONFIG_USER_MTDUTILS_DOC_LOADBIOS is not set
# CONFIG_USER_MTDUTILS_FLASHCP is not set
# CONFIG_USER_MTDUTILS_FLASH_ERASE is not set
# CONFIG_USER_MTDUTILS_FLASH_ERASEALL is not set
# CONFIG_USER_MTDUTILS_FLASH_LOCK is not set
# CONFIG_USER_MTDUTILS_FLASH_OTP_DUMP is not set
# CONFIG_USER_MTDUTILS_FLASH_OTP_INFO is not set
# CONFIG_USER_MTDUTILS_FLASH_UNLOCK is not set
# CONFIG_USER_MTDUTILS_FTL_CHECK is not set
# CONFIG_USER_MTDUTILS_FTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_JFFS2DUMP is not set
# CONFIG_USER_MTDUTILS_JFFS2READER is not set
# CONFIG_USER_MTDUTILS_MKFSJFFS2 is not set
# CONFIG_USER_MTDUTILS_MTD_DEBUG is not set
# CONFIG_USER_MTDUTILS_NANDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDTEST is not set
# CONFIG_USER_MTDUTILS_NANDWRITE is not set
# CONFIG_USER_MTDUTILS_NFTLDUMP is not set
# CONFIG_USER_MTDUTILS_NFTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_RECV_IMAGE is not set
# CONFIG_USER_MTDUTILS_RFDDUMP is not set
# CONFIG_USER_MTDUTILS_RFDFORMAT is not set
# CONFIG_USER_MTDUTILS_SERVE_IMAGE is not set
# CONFIG_USER_MTDUTILS_SUMTOOL is not set
# CONFIG_USER_MTDUTILS_MKFSUBIFS is not set
# CONFIG_USER_MTDUTILS_MTDINFO is not set
# CONFIG_USER_MTDUTILS_UBIATTACH is not set
# CONFIG_USER_MTDUTILS_UBICRC32 is not set
# CONFIG_USER_MTDUTILS_UBIDETACH is not set
# CONFIG_USER_MTDUTILS_UBIFORMAT is not set
# CONFIG_USER_MTDUTILS_UBIMKVOL is not set
# CONFIG_USER_MTDUTILS_UBINFO is not set
# CONFIG_USER_MTDUTILS_UBINIZE is not set
# CONFIG_USER_MTDUTILS_UBIRENAME is not set
# CONFIG_USER_MTDUTILS_UBIRMVOL is not set
# CONFIG_USER_MTDUTILS_UBIRSVOL is not set
# CONFIG_USER_MTDUTILS_UBIUPDATEVOL is not set

#
# Network Applications
#
# CONFIG_USER_3G is not set
CONFIG_USER_ACCEL_PPTP=y
CONFIG_USER_PPPD_WITH_PPTP=y
# CONFIG_USER_ARPTABLES is not set
# CONFIG_USER_BRCTL_BRCTL is not set
# CONFIG_USER_BIGPOND is not set
# CONFIG_USER_BT_UTILS is not set
# CONFIG_USER_BT_AVINFO is not set
# CONFIG_USER_BT_BCCMD is not set
# CONFIG_USER_BT_CIPTOOL is not set
# CONFIG_USER_BT_HCICONFIG is not set
# CONFIG_USER_BT_HCIATTACH is not set
# CONFIG_USER_BT_HCISECFILTER is not set
# CONFIG_USER_BT_HCITOOL is not set
# CONFIG_USER_BT_L2PING is not set
# CONFIG_USER_BT_PPPORC is not set
# CONFIG_USER_BT_SDPTOOL is not set
# CONFIG_USER_CTORRENT is not set
# CONFIG_USER_CPU is not set
# CONFIG_USER_DHCP6 is not set
# CONFIG_USER_DHCP6_SERVER is not set
# CONFIG_USER_DHCP6_CLIENT is not set
# CONFIG_USER_WIDE_DHCPV6 is not set
# CONFIG_USER_ISC_DHCP is not set
# CONFIG_USER_DROPBEAR is not set
CONFIG_USER_DNSMASQ=y
# CONFIG_USER_DISKTYPE is not set
# CONFIG_USER_ECHO_SERVER is not set
# CONFIG_USER_EBTABLES is not set
# CONFIG_USER_HOSTAPD is not set
CONFIG_USER_STORAGE=y
# CONFIG_USER_PROFTPD is not set
CONFIG_USER_SAMBA=y
CONFIG_SAMBA_3_0_2=y
# CONFIG_SAMBA_3_6_6 is not set
# CONFIG_SAMBA_4_0_24 is not set
CONFIG_USER_GOAHEAD_HOSTNAME=y
CONFIG_LIB_NSL_FORCE=y
# CONFIG_USER_NMBD_ONLY is not set
CONFIG_USER_SAMBA_ALL=y
# CONFIG_USER_MTDAAPD is not set
# CONFIG_USER_DNS_RESPONDER is not set
# CONFIG_USER_MINIDLNA is not set
# CONFIG_USER_DMS is not set
# CONFIG_LIB_LIBUPNP166_DMS_FORCE is not set
CONFIG_USER_LIGHTY=y
CONFIG_LIB_PCRE_FORCE=y
CONFIG_LIB_ZLIB_FORCE=y
# CONFIG_USER_GOAHEAD_HTTPD is not set
# CONFIG_USER_GOAHEAD_IPV6 is not set
# CONFIG_USER_GOAHEAD_SSL is not set
# CONFIG_USER_GOAHEAD_HOSTNAME is not set
# CONFIG_USER_GOAHEAD_GreenAP is not set
# CONFIG_USER_WIZARD is not set
# CONFIG_USER_GOAHEAD_LANG_EN is not set
# CONFIG_USER_GOAHEAD_LANG_ZHTW is not set
# CONFIG_USER_GOAHEAD_LANG_ZHCN is not set
CONFIG_USER_GOAHEAD_LANG_EN=y
# CONFIG_USER_ECMH is not set
CONFIG_USER_IGMP_PROXY=y
# CONFIG_USER_INADYN is not set
CONFIG_USER_IPTABLES_IPTABLES=y
CONFIG_LIB_LIBM_FORCE=y
# CONFIG_USER_IPTABLES_IP6TABLES is not set
CONFIG_USER_IPROUTE2=y
# CONFIG_USER_IPROUTE2_SS is not set
# CONFIG_USER_IPROUTE2_ARPD is not set
# CONFIG_USER_IPROUTE2_NSTAT is not set
# CONFIG_USER_IPROUTE2_IFSTAT is not set
# CONFIG_USER_IPROUTE2_RTACCT is not set
# CONFIG_USER_IPROUTE2_LNSTAT is not set
CONFIG_USER_IPROUTE2_IP=y
# CONFIG_USER_IPROUTE2_RTMON is not set
# CONFIG_USER_IPROUTE2_TC is not set
CONFIG_LIB_LIBM_FORCE=y
# CONFIG_USER_KAID is not set
# CONFIG_USER_MATRIXSSL is not set
CONFIG_USER_MINIUPNPD=y
CONFIG_USER_MKDOSFS=y
CONFIG_USER_NTPCLIENT_NTPCLIENT=y
# CONFIG_USER_NTPCLIENT_ADJTIMEX is not set
# CONFIG_USER_OPENSSL is not set
CONFIG_USER_OPENL2TP=y
CONFIG_USER_PPPD_WITH_L2TP=y
CONFIG_LIB_FLEX_FORCE=y
# CONFIG_USER_IPSEC_TOOLS is not set
# CONFIG_USER_OPENSWAN is not set
# CONFIG_USER_P910ND is not set
# CONFIG_USER_PARPROUTED is not set
CONFIG_USER_PPPD=y
CONFIG_USER_PPPD_WITH_PPPOE=y
CONFIG_USER_PPPD_WITH_L2TP=y
CONFIG_USER_PPPD_WITH_PPTP=y
# CONFIG_USER_PPPD_PPPSTATS is not set
# CONFIG_USER_PPPD_PPPDUMP is not set
# CONFIG_USER_PPPD_PPPCHAT is not set
# CONFIG_USER_RPPPPOE_RELAY is not set
# CONFIG_USER_RPPPPOE_SNIFF is not set
# CONFIG_USER_PPPOECD is not set
# CONFIG_USER_PPTP_CLIENT is not set
# CONFIG_USER_ZEBRA is not set
# CONFIG_LIB_LIBZEBRA_FORCE is not set
# CONFIG_USER_RP_L2TP is not set
CONFIG_USER_RADVD=y
# CONFIG_USER_RADVD_DUMP is not set
CONFIG_USER_802_1X=y
# CONFIG_USER_RT2561_802_1X is not set
# CONFIG_USER_SNORT is not set
# CONFIG_USER_SNMPD is not set
# CONFIG_USER_NETSNMP_SNMPD is not set
# CONFIG_USER_TOTD is not set
CONFIG_USER_UVC_STREAM=y
# CONFIG_USER_UPNP_IGD is not set
# CONFIG_USER_WPA_SUPPLICANT is not set
# CONFIG_USER_WSC is not set

#
# Wireless-tools
#
CONFIG_USER_WIRELESS_TOOLS=y
CONFIG_USER_WIRELESS_TOOLS_IWCONFIG=y
# CONFIG_USER_WIRELESS_TOOLS_IWGETID is not set
# CONFIG_USER_WIRELESS_TOOLS_IWLIST is not set
CONFIG_USER_WIRELESS_TOOLS_IWPRIV=y
# CONFIG_USER_WIRELESS_TOOLS_IWSPY is not set
# CONFIG_USER_WIRELESS_TOOLS_IWEVENT is not set

#
# Bluetooth-apps
#
# CONFIG_USER_BLUEANGEL is not set
# CONFIG_USER_BLUEANGEL_MTKBT is not set
# CONFIG_USER_BLUEANGEL_BTCLI is not set
# CONFIG_USER_BTCLI_ON is not set
# CONFIG_USER_BLUEANGEL_RELAYER is not set
# CONFIG_USER_BLUEANGEL_AUTOBT is not set
# CONFIG_BT_HCI_CMD is not set
# CONFIG_USER_ROUTER_PLAYER_NEW is not set

#
# Miscellaneous Applications
#
CONFIG_USER_BUSYBOX_BUSYBOX=y
# CONFIG_USER_BONNIE is not set
# CONFIG_USER_CACHEBENCH is not set
# CONFIG_USER_ETHTOOL is not set
# CONFIG_DHRYSTONE is not set
# CONFIG_DHCPFWD is not set
# CONFIG_USER_GDBREPLAY is not set
# CONFIG_USER_GDBSERVER is not set
# CONFIG_USER_IXIA_ENDPOINT is not set
# CONFIG_USER_IPERF is not set
# CONFIG_USER_I2C_TOOLS is not set
# CONFIG_USER_LMBENCH3 is not set
CONFIG_USER_MTD_WRITE=y
CONFIG_USER_MPSTAT=y
# CONFIG_USER_NBENCH is not set
# CONFIG_USER_NETCAT is not set
# CONFIG_USER_NETSTAT_NAT is not set
# CONFIG_USER_NTFS3G is not set
# CONFIG_USER_NTFSPROGS is not set
# CONFIG_LIB_LIBNTFS3G_FORCE is not set
# CONFIG_USER_STRACE_STRACE is not set
CONFIG_USER_TCPDUMP=y
# CONFIG_USER_TASKSET is not set
CONFIG_USER_PCIUTIL_LSPCI=y
# CONFIG_USER_PCIUTIL_SETPCI is not set
CONFIG_LIB_ZLIB_FORCE=y
# CONFIG_USER_LSUSB is not set
# CONFIG_USER_USBMODESWITCH is not set
# CONFIG_USER_COMGT is not set
# CONFIG_USER_SDPARM is not set
# CONFIG_USER_WATCHDOG is not set
# CONFIG_USER_VMSTAT is not set

#
# Proprietary Application
#
CONFIG_RALINKAPP=y
CONFIG_RALINKAPP_ATED=y
CONFIG_RALINKAPP_REG_RW=y
# CONFIG_RALINKAPP_CSR is not set
CONFIG_RALINKAPP_FLASH=y
CONFIG_FLASH_TOOL=y
CONFIG_ETHMAC_TOOL=y
CONFIG_RALINKAPP_HWNAT=y
# CONFIG_RALINKAPP_SWNAT is not set
CONFIG_RALINKAPP_MII_MGR=y
CONFIG_RALINKAPP_NVRAM=y
CONFIG_LIB_LIBNVRAM_FORCE=y
# CONFIG_RALINKAPP_L2_MANAGE is not set
CONFIG_RALINKAPP_GPIO=y
# CONFIG_RALINKAPP_SPI is not set
CONFIG_RALINKAPP_I2C=y
# CONFIG_RALINKAPP_TOUCH_PANEL is not set
CONFIG_RALINKAPP_MEMORY_USAGE=y
# CONFIG_USER_QOS is not set
# CONFIG_RALINKAPP_SWQOS is not set
# CONFIG_RALINKAPP_AUTO_WAN is not set
# CONFIG_RALINKAPP_SUPERDMZ is not set
CONFIG_RALINKAPP_SWITCH=y
CONFIG_RALINKAPP_QDMA=y
# CONFIG_RALINKAPP_DUMP_MT7530_PHY is not set
CONFIG_RALINKAPP_I2S=y
CONFIG_RALINKAPP_PCM=y
CONFIG_RALINKAPP_SPDIF=y
CONFIG_RALINKAPP_PCIE_PHY=y
# CONFIG_RALINKAPP_CLS is not set
CONFIG_RALINKAPP_HOTSPOT=y
CONFIG_RALINKAPP_WAPI=y
CONFIG_RALINKAPP_SCRIPTS=y
CONFIG_RALINKAPP_BUSARB=y
# CONFIG_RALINKAPP_ETHPHY is not set
# CONFIG_RALINKAPP_KPROFILE is not set
CONFIG_UFSD_TOOL=y
CONFIG_UFSD_NTFS_TOOL=y
CONFIG_UFSD_HFS_TOOL=y
CONFIG_UFSD_EXFAT_TOOL=y
# CONFIG_USER_NFCSD is not set
# CONFIG_USER_NFCHOD is not set
# CONFIG_USER_MET is not set
# CONFIG_USER_AB151X_TOOL is not set
# CONFIG_MTK_U3H_TEST is not set

#
# Windows Rally Program
#
CONFIG_USER_LLTD=y

#
# Phone Management
#
# CONFIG_MTK_VOIP is not set

#
# Remote Management
#
# CONFIG_MTK_TR069 is not set
