#! /bin/sh
if [ -f "/userfs/bin/tcapi" ];then
APPS_DEV=`/userfs/bin/tcapi get Apps_Entry apps_dev`
APPS_MOUNTED_PATH=`/userfs/bin/tcapi get Apps_Entry apps_mounted_path`
APPS_INSTALL_FOLDER=`/userfs/bin/tcapi get Apps_Entry apps_install_folder`
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER
APPS_SERVER=`/userfs/bin/tcapi get Apps_Entry apps_ipkg_server`
else
APPS_DEV=`nvram get apps_dev`
APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER
APPS_PATH=`nvram get apps_mounted_path |awk 'BEGIN{FS="/tmp/mnt/"}{print $2}'`
APPS_SERVER=`nvram get apps_ipkg_old`
is_arm_machine=`uname -m |grep arm`
fi
IPKG_ERROR=""


echo "check DM2 start"
#S50asuslighttpd check
if [ ! -f "$APPS_INSTALL_PATH/etc/init.d/S50asuslighttpd" ]; then
	cp -f $APPS_INSTALL_PATH/etc/asus_script/dm2_* $APPS_INSTALL_PATH/tmp/
	echo "asuslighttpd_ipk is error,we must reinstall it"
	LIGHTTPD_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/asuslighttpd.control" | grep Version`
	LIGHTTPD_VER=`echo $LIGHTTPD_VER | awk 'BEGIN{FS=": "}{print $2}'`
	$APPS_INSTALL_PATH/bin/ipkg remove asuslighttpd -force-depends
	#wget -c -q -t 2 -T 30 http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/asuslighttpd_"$LIGHTTPD_VER"_mipsbig.ipk -O /opt/tmp/asuslighttpd_"$LIGHTTPD_VER"_mipsbig.ipk
	wget -c -q  http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/asuslighttpd_"$LIGHTTPD_VER"_mipsbig.ipk -O /opt/tmp/asuslighttpd_"$LIGHTTPD_VER"_mipsbig.ipk
	IPKG_ERROR="asuslighttpd"
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/asuslighttpd_"$LIGHTTPD_VER"_mipsbig.ipk
	rm -f /opt/tmp/asuslighttpd_"$LIGHTTPD_VER"_mipsbig.ipk
	mv -f $APPS_INSTALL_PATH/tmp/dm2_* $APPS_INSTALL_PATH/etc/asus_script/
fi
#bin and shell script check
if [ -f "$APPS_INSTALL_PATH/bin/dm2_amulecmd" ] && [ -f "$APPS_INSTALL_PATH/bin/dm2_amuled" ] && [ -f "$APPS_INSTALL_PATH/bin/dm2_detect" ] && [ -f "$APPS_INSTALL_PATH/bin/dm2_nzbget" ] && [ -f "$APPS_INSTALL_PATH/bin/dm2_snarf" ] && [ -f "$APPS_INSTALL_PATH/bin/dm2_snarfmaster" ] && [ -f "$APPS_INSTALL_PATH/bin/dm2_transmission-daemon" ] && [ -f "$APPS_INSTALL_PATH/etc/asus_script/dm2_backup" ] && [ -f "$APPS_INSTALL_PATH/etc/asus_script/dm2_check_general" ] && [ -f "$APPS_INSTALL_PATH/etc/asus_script/dm2_usbget" ]; then
	echo "dm2_ipk is OK"
else
	echo "dm2_ipk is error,we must reinstall it"
	DM2_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/downloadmaster.control" | grep Version`
	DM2_VER=`echo $DM2_VER | awk 'BEGIN{FS=": "}{print $2}'`
	$APPS_INSTALL_PATH/bin/ipkg remove downloadmaster -force-depends
	#wget -c -q -t 2 -T 30 http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/downloadmaster_"$DM2_VER"_mipsbig.ipk -O /opt/tmp/downloadmaster_"$DM2_VER"_mipsbig.ipk
	wget -c -q http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/downloadmaster_"$DM2_VER"_mipsbig.ipk -O /opt/tmp/downloadmaster_"$DM2_VER"_mipsbig.ipk
	IPKG_ERROR="downloadmaster"
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/downloadmaster_"$DM2_VER"_mipsbig.ipk
	rm -f /opt/tmp/downloadmaster_"$DM2_VER"_mipsbig.ipk
#####################################
	APP_UCLIBC_VERSION=0.9.28

	PATH=$APPS_PATH/usr/bin:$APPS_PATH/bin:$APPS_PATH/usr/sbin:$APPS_PATH/sbin:$PATH
	unset LD_LIBRARY_PATH
	unset LD_PRELOAD

if [ -f "/userfs/bin/tcapi" ];then
	APPS_DEV=`/userfs/bin/tcapi get Apps_Entry apps_dev`
	APPS_MOUNTED_PATH=`/userfs/bin/tcapi get Apps_Entry apps_mounted_path`
	APPS_INSTALL_FOLDER=`/userfs/bin/tcapi get Apps_Entry apps_install_folder`
	APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

	LANGUAGE_R=`/userfs/bin/tcapi get SysInfo_Entry preferred_lang`

	PRODUCTID=`/userfs/bin/tcapi get SysInfo_Entry ProductName`
	LAN_IP=`/userfs/bin/tcapi get Lan_Entry IP`
	MISCR_HTTPPORT_X=`/userfs/bin/tcapi get Firewall_Entry misc_httpport_x`
	MISCR_HTTP_X=`/userfs/bin/tcapi get Firewall_Entry misc_http_x`
	HTTP_PASSWD=`/userfs/bin/tcapi get Account_Entry0 web_passwd`
	DDNS_ENABLE_X=`/userfs/bin/tcapi get Ddns_Entry Active`
	DDNS_HOSTNAME_X=`/userfs/bin/tcapi get Ddns_Entry MYHOST`
	RFW_ENABLE_X=`/userfs/bin/tcapi get Firewall_Entry fw_enable_x`
else
	APPS_DEV=`nvram get apps_dev`
	APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
	APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
	APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER
	LANGUAGE_R=`nvram get preferred_lang`
	PRODUCTID=`nvram get productid`
	LAN_IP=`nvram get lan_ipaddr`
	MISCR_HTTPPORT_X=`nvram get misc_httpport_x`
	MISCR_HTTP_X=`nvram get misc_http_x`
	HTTP_PASSWD=`nvram get http_passwd`
	DDNS_ENABLE_X=`nvram get ddns_enable_x`
	DDNS_HOSTNAME_X=`nvram get ddns_hostname_x`
	RFW_ENABLE_X=`nvram get fw_enable_x`
fi
	chmod -R 777 $APPS_INSTALL_PATH/bin/

	chmod -R 777 $APPS_INSTALL_PATH/etc

	if [ ! -d "$APPS_MOUNTED_PATH/Download2" ]; then
	mkdir -p $APPS_MOUNTED_PATH/Download2
	fi

	if [ ! -d "$APPS_MOUNTED_PATH/Download2/Complete" ]; then
	mkdir -p $APPS_MOUNTED_PATH/Download2/Complete
	fi

	if [ ! -d "$APPS_MOUNTED_PATH/Download2/config" ]; then
	mkdir -p $APPS_MOUNTED_PATH/Download2/config
	fi

	if [ ! -d "$APPS_MOUNTED_PATH/Download2/InComplete" ]; then
	mkdir -p $APPS_MOUNTED_PATH/Download2/InComplete
	fi

	if [ ! -d "$APPS_MOUNTED_PATH/Download2/.logs" ]; then
	mkdir -p $APPS_MOUNTED_PATH/Download2/.logs
	fi

	if [ ! -d "$APPS_MOUNTED_PATH/Download2/Seeds" ]; then
	mkdir -p $APPS_MOUNTED_PATH/Download2/Seeds
	fi

	if [ ! -d "/tmp/asus_app" ]; then
	mkdir -p /tmp/asus_app
	fi

	chmod -R 777 $APPS_MOUNTED_PATH/Download2
	chmod -R 777 $APPS_MOUNTED_PATH/Download2/Complete
	chmod -R 777 $APPS_MOUNTED_PATH/Download2/config
	chmod -R 777 $APPS_MOUNTED_PATH/Download2/InComplete
	chmod -R 777 $APPS_MOUNTED_PATH/Download2/.logs
	chmod -R 777 $APPS_MOUNTED_PATH/Download2/Seeds
	chmod -R 777 /tmp/asus_app

	#sh /tmp/APPS/DM2/Script/dm2_usbget start
	sh /tmp/APPS/DM2/Script/dm2_check_general general-check

	dir_control_file=$APPS_INSTALL_PATH/etc/dm2_general.conf


	dir_btcontrol_file=$APPS_INSTALL_PATH/etc/dm2_transmission.conf
if [ -f "/userfs/bin/tcapi" ];then
	NVRAM_CHECK_TRS=`/userfs/bin/tcapi get Apps_Entry trs_peer_port`
	if [ ! -f "$dir_btcontrol_file" ]; then
		if [ "$NVRAM_CHECK_TRS" = "no attribute information" ]; then
			echo "The $dir_btcontrol_file is not installed yet!"
			echo "Peer_port=51413">$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Auth_type=1">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Max_torrent_peer=60">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Max_peer=240">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Enable_dht=1">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Down_limit=0">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Down_rate=100">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Up_limit=0">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Up_rate=100">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Enable_pex=1">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Enable_peer_port=0">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf	
			apps_dl_share_port="51413"
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-save
		else
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-recover
			apps_dl_share_port=`/userfs/bin/tcapi get Apps_Entry trs_peer_port`
		fi
	else
		if [  "$NVRAM_CHECK_TRS" != "no attribute information" ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-backup
		else
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-save
		fi
		apps_dl_share_port=`cat "$dir_btcontrol_file" |grep "Peer_port=" |awk 'BEGIN{FS="="}{print $2}'`
	fi

	dir_ed2k_file=$APPS_INSTALL_PATH/etc/dm2_ed2k.conf
	NVRAM_CHECK_ED2K=`/userfs/bin/tcapi get Apps_Entry ed2k_ip`
	if [ ! -f "$dir_ed2k_file" ]; then
		if [  "$NVRAM_CHECK_ED2K" = "no attribute information" ]; then
			echo "server_ip=176.103.48.36">$APPS_INSTALL_PATH/etc/dm2_ed2k.conf
			echo "server_port=4184">>$APPS_INSTALL_PATH/etc/dm2_ed2k.conf
			ED2K_SERVER_IP="176.103.48.36"
			ED2K_SERVER_PORT="4184"
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvramsave
		else
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvramrecover
			ED2K_SERVER_IP=`/userfs/bin/tcapi get Apps_Entry ed2k_ip`
			ED2K_SERVER_PORT=`/userfs/bin/tcapi get Apps_Entry ed2k_port`
		fi
	else
		if [ "$NVRAM_CHECK_ED2K" != "no attribute information" ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvrambackup
		else
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvramsave
		fi
		ED2K_SERVER_IP=`/userfs/bin/tcapi get Apps_Entry ed2k_ip`
		ED2K_SERVER_PORT=`/userfs/bin/tcapi get Apps_Entry ed2k_port`
	fi
else
	NVRAM_CHECK_TRS=`nvram get trs_peer_port`
	if [ ! -f "$dir_btcontrol_file" ]; then
		if [ -z $NVRAM_CHECK_TRS ]; then
			echo "Peer_port=51413">$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Auth_type=1">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Max_torrent_peer=60">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Max_peer=240">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Enable_dht=1">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Down_limit=0">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Down_rate=100">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Up_limit=0">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Up_rate=100">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Enable_pex=1">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf
			echo "Enable_peer_port=0">>$APPS_INSTALL_PATH/etc/dm2_transmission.conf	
			apps_dl_share_port="51413"
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-save
		else
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-recover
			apps_dl_share_port=`nvram get trs_peer_port`
		fi
	else
		if [ ! -z $NVRAM_CHECK_TRS ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-backup
		else
			sh /tmp/APPS/DM2/Script/dm2_backup nvram-save
		fi
		apps_dl_share_port=`cat "$dir_btcontrol_file" |grep "Peer_port=" |awk 'BEGIN{FS="="}{print $2}'`
	fi

	dir_ed2k_file=$APPS_INSTALL_PATH/etc/dm2_ed2k.conf
	NVRAM_CHECK_ED2K=`nvram get ed2k_ip`
	if [ ! -f "$dir_ed2k_file" ]; then
		if [ -z $NVRAM_CHECK_ED2K ]; then
			echo "server_ip=176.103.48.36">$APPS_INSTALL_PATH/etc/dm2_ed2k.conf
			echo "server_port=4184">>$APPS_INSTALL_PATH/etc/dm2_ed2k.conf
			ED2K_SERVER_IP="176.103.48.36"
			ED2K_SERVER_PORT="4184"
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvramsave
		else
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvramrecover
			ED2K_SERVER_IP=`nvram get ed2k_ip`
			ED2K_SERVER_PORT=`nvram get ed2k_port`
		fi
	else
		if [ ! -z $NVRAM_CHECK_ED2K ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvrambackup
		else
			sh /tmp/APPS/DM2/Script/dm2_backup ed2k-nvramsave
		fi
		ED2K_SERVER_IP=`nvram get ed2k_ip`
		ED2K_SERVER_PORT=`nvram get ed2k_port`
	fi

fi
	while [ ! -f "$dir_control_file" ]
	do
		sleep 2
	done

	DEVICE_TYPE_CHECK_TMP=`cat "$dir_control_file" |grep "DEVICE_TYPE="`
	while [ "$DEVICE_TYPE_CHECK_TMP" = "" ]
	do
		DEVICE_TYPE_CHECK_TMP=`cat "$dir_control_file" |grep "DEVICE_TYPE="`
		sleep 2
	done

if [ -f "/userfs/bin/tcapi" ];then
	BASE_PATH=`/userfs/bin/tcapi show Apps_Entry |grep "apps_mounted_path" |awk 'BEGIN{FS="/"}{print $4}'`
	MISC_HTTP_X=`cat "$dir_control_file" |grep "MISC_HTTP_X=" |awk 'BEGIN{FS="="}{print $2}'`
	APPS_DL_SHARE=`cat "$dir_control_file" |grep "APPS_DL_SHARE=" |awk 'BEGIN{FS="="}{print $2}'`
	DM_PORT=`cat "$dir_control_file" |grep "DM_PORT=" |awk 'BEGIN{FS="="}{print $2}'`
	DOWNLOAD_PATH=`cat "$dir_control_file" |grep "Download_dir=" |awk 'BEGIN{FS="="}{print $2}'`
	DOWNLOAD_PATH_ED2K=`echo $DOWNLOAD_PATH|sed -n 's/\//\\\\\//pg'`

	sh /tmp/APPS/DM2/Script/dm2_backup generalnvram-save

	NZB_TEST=`/userfs/bin/tcapi get Apps_Entry nzb_host`
	if [ -f "$APPS_INSTALL_PATH/etc/dm2_nzbget_EX.conf" ]; then
		if [ "$NZB_TEST" = "no attribute information" ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup nzb-nvramsave
		else
			sh /tmp/APPS/DM2/Script/dm2_backup nzb-nvrambackup
		fi
	else
		if [ "$NZB_TEST" != "no attribute information"  ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup nzb-nvramrecover		
		fi
	fi
else
	BASE_PATH=`nvram get apps_mounted_path |awk 'BEGIN{FS="/"}{print $4}'`
	MISC_HTTP_X=`cat "$dir_control_file" |grep "MISC_HTTP_X=" |awk 'BEGIN{FS="="}{print $2}'`
	APPS_DL_SHARE=`cat "$dir_control_file" |grep "APPS_DL_SHARE=" |awk 'BEGIN{FS="="}{print $2}'`
	DM_PORT=`cat "$dir_control_file" |grep "DM_PORT=" |awk 'BEGIN{FS="="}{print $2}'`
	DOWNLOAD_PATH=`cat "$dir_control_file" |grep "Download_dir=" |awk 'BEGIN{FS="="}{print $2}'`
	DOWNLOAD_PATH_ED2K=`echo $DOWNLOAD_PATH|sed -n 's/\//\\\\\//pg'`

	sh /tmp/APPS/DM2/Script/dm2_backup generalnvram-save
	NZB_TEST=`nvram get nzb_host`
	if [ -f "$APPS_INSTALL_PATH/etc/dm2_nzbget_EX.conf" ]; then
		if [ -z $NZB_TEST ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup nzb-nvramsave
		else
			sh /tmp/APPS/DM2/Script/dm2_backup nzb-nvrambackup
		fi
	else
		if [ ! -z $NZB_TEST ]; then
			sh /tmp/APPS/DM2/Script/dm2_backup nzb-nvramrecover		
		fi
	fi
fi

fi

#wxbase
WXBASE=`ls $APPS_INSTALL_PATH/lib/ |grep libwx_baseu-`
WXBASE_EXIST=0
for wxbaseobj in $WXBASE; do
	if [ -L "$APPS_INSTALL_PATH/lib/$wxbaseobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$wxbaseobj" ]; then
		WXBASE_EXIST=1;
		break;
	fi
done
WXBASENET=`ls $APPS_INSTALL_PATH/lib/ |grep libwx_baseu_net-`
WXBASENET_EXIST=0
for wxbasenetobj in $WXBASENET; do
	if [ -L "$APPS_INSTALL_PATH/lib/$wxbasenetobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$wxbasenetobj" ]; then
		WXBASENET_EXIST=1
		break;
	fi
done
if [ $WXBASE_EXIST -eq 0 ] || [ $WXBASENET_EXIST -eq 0 ]; then
	echo "WXBASE_IPKG is error, we must reinstall it"
	WX_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/wxbase.control" | grep Version`
	WX_VER=`echo $WX_VER | awk 'BEGIN{FS=": "}{print $2}'`
	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/wxbase_"$WX_VER"_mipsbig.ipk
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/wxbase_"$WX_VER"_mipsbig.ipk
	IPKG_ERROR="wxbase"
	rm -f /opt/tmp/wxbase_"$WX_VER"_mipsbig.ipk
fi
#libreadline
READLINE=`ls $APPS_INSTALL_PATH/lib/ |grep libreadline.so`
READLINE_EXIST=0
for readlineobj in $READLINE; do
	if [ -L "$APPS_INSTALL_PATH/lib/$readlineobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$readlineobj" ]; then
		READLINE_EXIST=1;
		break;
	fi
done
if [ $READLINE_EXIST -eq 0 ]; then
	echo "READLINE_IPKG is error, we must reinstall it"
	READLINE_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/readline.control" | grep Version`
	READLINE_VER=`echo $READLINE_VER | awk 'BEGIN{FS=": "}{print $2}'`
	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/readline_"$READLINE_VER"_mipsbig.ipk
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/readline_"$READLINE_VER"_mipsbig.ipk
	IPKG_ERROR="readline"
	rm -f /opt/tmp/readline_"$READLINE_VER"_mipsbig.ipk
fi
#expat
EXPAT=`ls $APPS_INSTALL_PATH/lib/ |grep libexpat.so`
EXPAT_EXIST=0
for expatobj in $EXPAT; do
	if [ -L "$APPS_INSTALL_PATH/lib/$expatobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$expatobj" ]; then
		EXPAT_EXIST=1;
		break;
	fi
done
if [ $EXPAT_EXIST -eq 0 ]; then
	echo "EXPAT_IPKG is error,we must reinstall it"
	EXPAT_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/expat.control" | grep Version`
	EXPAT_VER=`echo $EXPAT_VER | awk 'BEGIN{FS=": "}{print $2}'`
	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/expat_"$EXPAT_VER"_mipsbig.ipk
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/expat_"$EXPAT_VER"_mipsbig.ipk
	IPKG_ERROR="expat"
	rm -f /opt/tmp/expat_"$EXPAT_VER"_mipsbig.ipk
fi
#libcurl
#CURL=`ls $APPS_INSTALL_PATH/lib/ |grep libcurl.so`
#CURL_EXIST=0
#for curlobj in $CURL; do
#	if [ -L "$APPS_INSTALL_PATH/lib/$curlobj" ]; then
#		continue;
#	elif [ -f "$APPS_INSTALL_PATH/lib/$curlobj" ]; then
#		CURL_EXIST=1; 
#		break;
#	fi
#done
#if [ $CURL_EXIST -eq 0 ]; then
#	echo "CURL_IPKG is error, we must reinstall it"
#	CURL_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/libcurl.control" | grep Version`
#	CURL_VER=`echo $CURL_VER | awk '{FS=": ";print $2}'`
#	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/libcurl_"$CURL_VER"_mipsbig.ipk
#	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/libcurl_"$CURL_VER"_mipsbig.ipk
#	rm -f /opt/tmp/libcurl_"$CURL_VER"_mipsbig.ipk
#fi
#libevent
EVENT=`ls $APPS_INSTALL_PATH/lib/ |grep libevent-`
EVENT_EXIST=0
for eventobj in $EVENT; do
	if [ -L "$APPS_INSTALL_PATH/lib/$eventobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$eventobj" ]; then
		EVENT_EXIST=1;
		break;
	fi
done
if [ $EVENT_EXIST -eq 0 ]; then
	echo "EVENT_IPKG is error, we must reinstall it"
	EVENT_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/libevent.control" | grep Version`
	EVENT_VER=`echo $EVENT_VER | awk 'BEGIN{FS=": "}{print $2}'`
	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/libevent_"$EVENT_VER"_mipsbig.ipk
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/libevent_"$EVENT_VER"_mipsbig.ipk
	IPKG_ERROR="libevent"
	rm -f /opt/tmp/libevent_"$EVENT_VER"_mipsbig.ipk
fi
#libpar2
#PAR2=`ls $APPS_INSTALL_PATH/lib/ |grep libpar2.so`
#PAR2_EXIST=0
#for par2obj in $PAR2; do
#	if [ -L "$APPS_INSTALL_PATH/lib/$par2obj" ]; then
#		continue;
#	elif [ -f "$APPS_INSTALL_PATH/lib/$par2obj" ]; then
#		PAR2_EXIST=1;
#		break;
#	fi
#done
#if [ $PAR2_EXIST -eq 0 ]; then
#	echo "PAR2_IPKG is error, we must reinstall it"
#	PAR2_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/libpar2.control" | grep Version`
#	PAR2_VER=`echo $PAR2_VER | awk '{FS=": ";print $2}'`
#	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/libpar2_"$PAR2_VER"_mipsbig.ipk
#	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/libpar2_"$PAR2_VER"_mipsbig.ipk
#	rm -f /opt/tmp/libpar2_"$PAR2_VER"_mipsbig.ipk
#fi
#libsigc++
#SIGC=`ls $APPS_INSTALL_PATH/lib/ |grep libsigc`
#SIGC_EXIST=0
#for sigcobj in $SIGC; do
#	if [ -L "$APPS_INSTALL_PATH/lib/$sigcobj" ]; then
#		continue;
#	elif [ -f "$APPS_INSTALL_PATH/lib/$sigcobj" ]; then
#		SIGC_EXIST=1;
#		break;
#	fi
#done
#if [ $SIGC_EXIST -eq 0 ]; then
#	echo "SIGC_IPKG is error, we must reinstall it"
#	SIGC_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/libsigc++.control" | grep Version`
#	SIGC_VER=`echo $SIGC_VER | awk '{FS=": ";print $2}'`
#	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/libsigc++_"$SIGC_VER"_mipsbig.ipk
#	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/libsigc++_"$SIGC_VER"_mipsbig.ipk
#	rm -f /opt/tmp/libsigc++_"$SIGC_VER"_mipsbig.ipk
#fi
#libxml
XML=`ls $APPS_INSTALL_PATH/lib/ |grep libxml2.so`
XML_EXIST=0
for xmlobj in $XML; do
	if [ -L "$APPS_INSTALL_PATH/lib/$xmlobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$xmlobj" ]; then
		XML_EXIST=1;
		break;
	fi
done
if [ $XML_EXIST -eq 0 ]; then
	echo "XML_IPKG is error, we must reinstall it"
	XML_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/libxml2.control" | grep Version`
	XML_VER=`echo $XML_VER | awk 'BEGIN{FS=": "}{print $2}'`
	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/libxml2_"$XML_VER"_mipsbig.ipk
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/libxml2_"$XML_VER"_mipsbig.ipk
	IPKG_ERROR="libxml2"
	rm -f /opt/tmp/libxml2_"$XML_VER"_mipsbig.ipk
fi
#ncurses
NCURSES=`ls $APPS_INSTALL_PATH/lib/ | grep libncurses.so`
NCURSES_EXIST=0
for ncursesobj in $NCURSES; do
	if [ -L "$APPS_INSTALL_PATH/lib/$ncursesobj" ]; then
		continue;
	elif [ -f "$APPS_INSTALL_PATH/lib/$ncursesobj" ]; then
		NCURSES_EXIST=1;
		break;
	fi
done
if [ $NCURSES_EXIST -eq 0 ]; then
	echo "NCURSES_IPKG is error, we must reinstall it"
	NCURSES_VER=`cat "$APPS_INSTALL_PATH/lib/ipkg/info/ncurses.control" | grep Version`
	NCURSES_VER=`echo $NCURSES_VER | awk 'BEGIN{FS=": "}{print $2}'`
	wget -q -P /opt/tmp http://nw-dlcdnet.asus.com/asusware/mipsbig/stable/ncurses_"$NCURSES_VER"_mipsbig.ipk
	$APPS_INSTALL_PATH/bin/ipkg install /opt/tmp/ncurses_"$NCURSES_VER"_mipsbig.ipk
	IPKG_ERROR="ncurses"
	rm -f /opt/tmp/ncurses_"$NCURSES_VER"_mipsbig.ipk
fi
if [ -n "$IPKG_ERROR" ]; then
	app_base_link.sh
	app_base_library.sh
	app_move_to_pool.sh $APPS_DEV
fi
echo "check DM2 end"
