#
# Makefile for the kernel USB device drivers.
#

# Object files in subdirectories

#obj-$(CONFIG_RALINK_I2C_CODEC)          += codec/
#obj-$(CONFIG_RALINK_I2S)        	+= core/


clean:
	rm -rf ./*.mod.* ./*.ko ./*.o ./*.bak ./.*.cmd
	rm -fr modules.order
	rm -ff modules.builtin
