#! /bin/sh

is_arm_machine=`uname -m |grep arm`

APP_UCLIBC_VERSION=0.9.28

#PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/bin
if [ -f "/userfs/bin/tcapi" ];then
	APPS_DEV=`/userfs/bin/tcapi get Apps_Entry apps_dev`
	APPS_MOUNTED_PATH=`/userfs/bin/tcapi get Apps_Entry apps_mounted_path`
	APPS_INSTALL_FOLDER=`/userfs/bin/tcapi get Apps_Entry apps_install_folder`
	APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER

	LANGUAGE_R=`/userfs/bin/tcapi get SysInfo_Entry preferred_lang`

	PRODUCTID=`/userfs/bin/tcapi get SysInfo_Entry ProductName`
	LAN_IP=`/userfs/bin/tcapi get Lan_Entry IP`
	MISCR_HTTPPORT_X=`/userfs/bin/tcapi get Firewall_Entry misc_httpport_x`
	MISCR_HTTP_X=`/userfs/bin/tcapi get Firewall_Entry misc_http_x`
#get Wan ip in DSL-wrt, by judging the dualwan status to get the real ip
	DualWan=`/userfs/bin/tcapi get Dualwan_Entry wans_dualwan`
	if [ -n "$DualWan" ] || [ "$DualWan" != "no attribute information" ] || [ "$DualWan" != "none" ]
	then
		Pri_Wan=`echo $DualWan | awk '{printf("%s\n", $1);}'`
		Sec_Wan=`echo $DualWan | awk '{printf("%s\n", $2);}'`
	
		#get the first wan type
		if [ "$Pri_Wan" = "lan" ]; then
			Pri_unit=12
		elif [ "$Pri_Wan" = "usb" ]; then
			Pri_unit=11
		elif [ "$Pri_Wan" = "wan" ]; then
			Pri_unit=10
		elif [ "$Pri_Wan" = "dsl" ]; then
			DSLMode=`/userfs/bin/tcapi get Wan_Common DSLMode`
			if [ "$DSLMode" = "VDSL" ]
			then
				Pri_unit=8
			else 
				Pri_unit=0
			fi
		fi
		Pri_Wan_IP=`/userfs/bin/tcapi get Wanduck_Common wan"$Pri_unit"_ipaddr`
		#get sec wan type, if sec_wan=none then jump this
		if [ "$Sec_Wan" != "none" ]; then
			if [ "$Sec_Wan" = "lan" ]; then
				Sec_unit=12
			elif [ "$Sec_Wan" = "usb" ]; then
				Sec_unit=11
			elif [ "$Sec_Wan" = "wan" ]; then
				Sec_unit=10
			elif [ "$Sec_Wan" = "dsl" ]; then
				DSLMode2=`/userfs/bin/tcapi get Wan_Common DSLMode`
				if [ "$DSLMode2" = "VDSL" ]
				then
					Sec_unit=8
				else
					Sec_unit=0
				fi
			fi

			Sec_Wan_IP=`/userfs/bin/tcapi get Wanduck_Common wan"$Sec_unit"_ipaddr`
	
			if [ -z "$Pri_Wan_IP" ] || [ "$Pri_Wan_IP" = "no attribute information" ] \
			|| [ "$Pri_Wan_IP" = "0.0.0.0" ]
			then
				#use 0.0.0.0 instead of "no attribute information"
				if [ -z "$Sec_Wan_IP" ] || [ "$Sec_Wan_IP" = "no attribute information" ]
				then
					WAN_IP="0.0.0.0"
				else
					WAN_IP=$Sec_Wan_IP
				fi
			else
				WAN_IP=$Pri_Wan_IP
			fi
		else
		#use 0.0.0.0 instead of "no attribute information"
			if [ -z "$Pri_Wan_IP" ] || [ "$Pri_Wan_IP" = "no attribute information" ]
			then
				WAN_IP="0.0.0.0"
			else
				WAN_IP=$Pri_Wan_IP
			fi
		fi
	else
		unit=`/userfs/bin/tcapi get Wanduck_Common wan_primary`
		WAN_IP=`/userfs/bin/tcapi get Wanduck_Common wan"$unit"_ipaddr`
		if [ -z "$Pri_Wan_IP" ] || [ "$Pri_Wan_IP" = "no attribute information" ]
		then
			WAN_IP="0.0.0.0"
		fi
	fi
	
	DDNS_ENABLE_X=`/userfs/bin/tcapi get Ddns_Entry Active`
	DDNS_HOSTNAME_X=`/userfs/bin/tcapi get Ddns_Entry MYHOST`
	RFW_ENABLE_X=`/userfs/bin/tcapi get Firewall_Entry fw_enable_x`

	DM_HTTP_PORT=`/userfs/bin/tcapi get Apps_Entry dm_http_port`
	DM_HTTPS_PORT=`/userfs/bin/tcapi get Apps_Entry dm_https_port`	
else
	APPS_MOUNTED_PATH=`nvram get apps_mounted_path`
	APPS_INSTALL_FOLDER=`nvram get apps_install_folder`
	APPS_INSTALL_PATH=$APPS_MOUNTED_PATH/$APPS_INSTALL_FOLDER
	APPS_DEV=`nvram get apps_dev`

	LANGUAGE_R=`nvram get preferred_lang`

	PRODUCTID=`nvram get productid`
	LAN_IP=`nvram get lan_ipaddr`
	MISCR_HTTPPORT_X=`nvram get misc_httpport_x`
	MISCR_HTTP_X=`nvram get misc_http_x`
	WAN_IP=`nvram get wan0_ipaddr`
	DDNS_ENABLE_X=`nvram get ddns_enable_x`
	DDNS_HOSTNAME_X=`nvram get ddns_hostname_x`
	RFW_ENABLE_X=`nvram get fw_enable_x`
	LOCAL_DOMAIN=`nvram get local_domain`

	DM_HTTP_PORT=`nvram get dm_http_port`
	DM_HTTPS_PORT=`nvram get dm_https_port`
fi
#chmod -R 777 $APPS_INSTALL_PATH/bin/

#chmod -R 777 $APPS_INSTALL_PATH/etc

if [ ! -d "/tmp/APPS/Lighttpd/Script/" ]; then
	mkdir -p /tmp/APPS/Lighttpd/Script/
fi
if [ ! -d "/tmp/APPS/Lighttpd/Config/" ]; then
	mkdir -p /tmp/APPS/Lighttpd/Config/
fi
if [ ! -d " /tmp/APPS/Lighttpd/compress/" ]; then
	mkdir -p /tmp/APPS/Lighttpd/compress/
fi

if [  -f "/userfs/bin/tcapi" ];then
	if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
		rm -rf /tmp/asus_router.conf
		cp -rf /opt/etc/asus_script/asus* /tmp/APPS/Lighttpd/Script/
		cp -rf /opt/etc/asus_lighttpd.conf /tmp/APPS/Lighttpd/Config/asus_lighttpd.conf
		cp -rf /opt/etc/init.d/S50asuslighttpd /tmp/APPS/Lighttpd/Script/S50asuslighttpd
		if [ ! -x "/tmp/APPS/Lighttpd" ] || [ ! -x "/tmp/APPS" ];then
			chmod -R 777 /tmp/APPS
		fi
                if [ ! -f "/opt/etc/asus_lighttpd/server.pem" ]; then
		sh /opt/etc/asus_script/gencert.sh
	        fi
	fi

	if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
		sh /tmp/APPS/Lighttpd/Script/asus_check_general general-check
	fi

	if [ ! -f "/opt/lib/ipkg/info/bzip2.control" ];then
		ipkg install /usr/bzip2_1.0.6-1_mipsbig.ipk
		sleep 2	
		cp -rf /opt/lib/libbz2.so.1.0.6 $APPS_INSTALL_PATH/lib
	fi
else
	if [ "$1" == "start" ] || [ "$1" == "restart" ]; then
		rm -rf /tmp/asus_router.conf
		cp -rf /opt/etc/asus_script/asus* /tmp/APPS/Lighttpd/Script/
		cp -rf /opt/etc/asus_lighttpd.conf /tmp/APPS/Lighttpd/Config/asus_lighttpd.conf
		cp -rf /opt/etc/init.d/S50asuslighttpd /tmp/APPS/Lighttpd/Script/S50asuslighttpd
		if [ ! -x "/tmp/APPS/Lighttpd" ] || [ ! -x "/tmp/APPS" ];then
			chmod -R 777 /tmp/APPS
		fi
		if [ ! -f "/opt/etc/asus_lighttpd/server.pem" ]; then
		sh /opt/etc/asus_script/gencert.sh
		fi
	fi

	if [ "$1" == "start" ] || [ "$1" == "restart" ]; then
		sh /tmp/APPS/Lighttpd/Script/asus_check_general general-check
	fi
	if [ ! -f "/opt/lib/ipkg/info/bzip2.control" ];then
		ipkg install /rom/bzip2_1.0.6-1_mipsbig.ipk
		sleep 2	
		cp -rf /opt/lib/libbz2.so.1.0.6 $APPS_INSTALL_PATH/lib
	fi
fi


dir_control_file=$APPS_INSTALL_PATH/etc/dm2_general.conf

	if [ ! -f "$dir_control_file" ]; then
		echo $dir_control_file
	else
	MISC_HTTP_X_TMP=`cat "$dir_control_file" |grep "MISC_HTTP_X="`
	MISC_HTTP_X=`echo $MISC_HTTP_X_TMP |awk 'BEGIN{FS="= "}{print $2}'`
	#MISC_HTTP_X=${MISC_HTTP_X_TMP:12}
	APPS_DL_SHARE_TMP=`cat "$dir_control_file" |grep "APPS_DL_SHARE="`
	#APPS_DL_SHARE=${APPS_DL_SHARE_TMP:14}
	APPS_DL_SHARE=`echo $APPS_DL_SHARE_TMP |awk 'BEGIN{FS="= "}{print $2}'`
	DM_PORT_TMP=`cat "$dir_control_file" |grep "DM_PORT="`
	#DM_PORT=${DM_PORT_TMP:8}
	DM_PORT=`echo $DM_PORT_TMP |awk 'BEGIN{FS="= "}{print $2}'`
	fi

	if [ ! -f "$APPS_INSTALL_PATH/etc/asus_lighttpd.conf" ]; then
		sh /tmp/APPS/Lighttpd/Script/asus_lighttpd_backup recover
	else
		#CONFIG_PORT=`cat "$APPS_INSTALL_PATH/etc/asus_lighttpd.conf" | grep "server.port"`
		#CONFIG_PORT=${CONFIG_PORT:14}
		CONFIG_PORT=`cat "$APPS_INSTALL_PATH/etc/asus_lighttpd.conf" | grep "server.port" |awk 'BEGIN{FS="= "}{print $2}'`
		#CONFIG_HTTPS_PORT=`cat "$APPS_INSTALL_PATH/etc/asus_lighttpd.conf" | grep "\$SERVER"`
		#CONFIG_HTTPS_PORT=${CONFIG_HTTPS_PORT:23:4}
		CONFIG_HTTPS_PORT=`cat "$APPS_INSTALL_PATH/etc/asus_lighttpd.conf" |grep '$SERVE' |awk 'BEGIN{FS="\":"}{print $2}'|awk 'BEGIN{FS="\""}{print $1}'`
		if [ -n "$DM_HTTP_PORT" ]&&[ "$DM_HTTP_PORT" != "$CONFIG_PORT" ] && [ "$DM_HTTP_PORT" != "no attribute information" ]; then
		    #"no attribute information for DSL Mipsbig Only"
			sed -i "96s/^.*$/server.port = $DM_HTTP_PORT/" $APPS_INSTALL_PATH/etc/asus_lighttpd.conf
			cp -rf $APPS_INSTALL_PATH/etc/asus_lighttpd.conf /tmp/APPS/Lighttpd/Config/asus_lighttpd.conf
		fi
		if [ -n "$DM_HTTPS_PORT" ] && [ "$DM_HTTPS_PORT" != "no attribute information" ] && [ "$DM_HTTPS_PORT" != "$CONFIG_HTTPS_PORT" ]; then
			sed -i "413s/^.*$/\$SERVER[\"socket\"] == \":$DM_HTTPS_PORT\" {/" $APPS_INSTALL_PATH/etc/asus_lighttpd.conf
			cp -rf $APPS_INSTALL_PATH/etc/asus_lighttpd.conf /tmp/APPS/Lighttpd/Config/asus_lighttpd.conf
		fi
	fi

case "$1" in
  start|force-reload|restart)
    #echo -n "Starting DM: "
	#sh $APPS_INSTALL_PATH/etc/init.d/dm2_base_link.sh&
	sh /tmp/APPS/Lighttpd/Script/asuslighttpd_check

	if [ -z "$APPS_MOUNTED_PATH" ]; then
		#nvram set apps_state_error=2
		/userfs/bin/tcapi set Apps_Entry apps_state_error=2
		exit 1
	fi

	APP_BIN=$APPS_INSTALL_PATH/bin
	APP_LIB=$APPS_INSTALL_PATH/lib

	APP_LINK_DIR=/tmp/opt
	APP_LINK_BIN=$APP_LINK_DIR/bin
	APP_LINK_LIB=$APP_LINK_DIR/lib

	rm -rf /tmp/getdiskinfo_lock&
	rm -rf /tmp/APPS/DM2/Status/cgi_running&
	rm -rf /tmp/APPS/Lighttpd/compress/downloadmaster&
	if [ ! -f "/userfs/bin/tcapi" ];then
		rm -rf $APP_LIB/libdl.so*
	fi

	APPS_MOUNTED_TYPE=`mount |grep "/dev/$APPS_DEV on " |awk '{print $5}'`
	if [ "$APPS_MOUNTED_TYPE" != "vfat" ] && [ "$APPS_MOUNTED_TYPE" != "tfat" ]; then
		#if [ ! -L "$APP_LINK_DIR" ]; then
                #rm -rf $APP_LINK_DIR
                #ln -sf $APPS_INSTALL_PATH $APP_LINK_DIR
        	#fi

		if [ ! -f "$APP_LIB/libpcre.so.1" ] && [ ! -f "$APP_LIB/libpcre.so.1.*" ]; then
			ln -sf 	$APP_LIB/libpcre.so.0.0.1 $APP_LIB/libpcre.so.1
		fi
		if [ ! -f "$APP_LIB/libpcre.so.0" ] && [ ! -f "$APP_LIB/libpcre.so.0.0.1" ]; then
				PCER_VER=`ls $APP_LIB/libpcre.so.1.* |awk 'BEGIN{FS=".so.1."}{print $2}'`
				ln -sf 	$APP_LIB/libpcre.so.1.$PCER_VER $APP_LIB/libpcre.so.0
		fi
		killall -SIGTERM asus_lighttpd&
		sleep 3

		cd  /opt/bin
		./asus_lighttpd -Df /opt/etc/asus_lighttpd.conf&
		exit 0
	fi

	# openssl
	OPENSSL_VER=`ls $APP_LIB/libcrypto.so.* |awk 'BEGIN{FS="libcrypto.so."}{print $2}'`
	ln -sf $APP_LIB/libcrypto.so.$OPENSSL_VER $APP_LINK_LIB/libcrypto.so.0
	ln -sf $APP_LIB/libcrypto.so.$OPENSSL_VER $APP_LINK_LIB/libcrypto.so
	ln -sf $APP_LIB/libssl.so.$OPENSSL_VER $APP_LINK_LIB/libssl.so.0
	ln -sf $APP_LIB/libssl.so.$OPENSSL_VER $APP_LINK_LIB/libssl.so

	# zlib
	ZLIB_VER=`ls $APP_LIB/libz.so.* |awk 'BEGIN{FS="libz.so."}{print $2}'`
	ln -sf $APP_LIB/libz.so.$ZLIB_VER $APP_LINK_LIB/libz.so.1
	ln -sf $APP_LIB/libz.so.$ZLIB_VER $APP_LINK_LIB/libz.so

	# bzip2
	BZIP2_VER=`ls $APP_LIB/libbz2.so.* |awk 'BEGIN{FS="libbz2.so."}{print $2}'`
	ln -sf $APP_LIB/libbz2.so.$BZIP2_VER $APP_LINK_LIB/libbz2.so.1.0
	ln -sf $APP_LIB/libbz2.so.$BZIP2_VER $APP_LINK_LIB/libbz2.so

	# ncurses
	NCURSES_VER=`ls $APP_LIB/libform.so.* |awk 'BEGIN{FS="libform.so."}{print $2}'`
	ln -sf $APP_LIB/libform.so.$NCURSES_VER $APP_LINK_LIB/libform.so.5
	ln -sf $APP_LIB/libform.so.$NCURSES_VER $APP_LINK_LIB/libform.so
	ln -sf $APP_LIB/libmenu.so.$NCURSES_VER $APP_LINK_LIB/libmenu.so.5
	ln -sf $APP_LIB/libmenu.so.$NCURSES_VER $APP_LINK_LIB/libmenu.so
	ln -sf $APP_LIB/libncurses.so.$NCURSES_VER $APP_LINK_LIB/libncurses.so.5
	ln -sf $APP_LIB/libncurses.so.$NCURSES_VER $APP_LINK_LIB/libncurses.so
	ln -sf $APP_LIB/libpanel.so.$NCURSES_VER $APP_LINK_LIB/libpanel.so.5
	ln -sf $APP_LIB/libpanel.so.$NCURSES_VER $APP_LINK_LIB/libpanel.so
	ln -sf $APP_LIB/../share/terminfo $APP_LINK_LIB/terminfo

	if [ -z "$is_arm_machine" ]; then
		# libuclibc++
		LIBCPLUS_VER=`ls $APP_LIB/libuClibc++-* |awk 'BEGIN{FS="libuClibc++"}{print $2}' |awk 'BEGIN{FS="-"}{print $2}' |awk 'BEGIN{FS=".so"}{print $1}'`
		ln -sf $APP_LIB/libuClibc++-$LIBCPLUS_VER.so $APP_LINK_LIB/libuClibc++.so.0
		ln -sf $APP_LIB/libuClibc++-$LIBCPLUS_VER.so $APP_LINK_LIB/libuClibc++.so
	fi

	# pcre
	PCRE1_VER=`ls $APP_LIB/libpcre.so.* |awk 'BEGIN{FS="libpcre.so."}{print $2}'`
	ln -sf $APP_LIB/libpcre.so.$PCRE1_VER $APP_LINK_LIB/libpcre.so.1
	ln -sf $APP_LIB/libpcre.so.$PCRE1_VER $APP_LINK_LIB/libpcre.so.0
	ln -sf $APP_LIB/libpcre.so.$PCRE1_VER $APP_LINK_LIB/libpcre.so
	PCRE2_VER=`ls $APP_LIB/libpcrecpp.so.* |awk 'BEGIN{FS="libpcrecpp.so."}{print $2}'`
	ln -sf $APP_LIB/libpcrecpp.so.$PCRE2_VER $APP_LINK_LIB/libpcrecpp.so.1
	ln -sf $APP_LIB/libpcrecpp.so.$PCRE2_VER $APP_LINK_LIB/libpcrecpp.so.0
	ln -sf $APP_LIB/libpcrecpp.so.$PCRE2_VER $APP_LINK_LIB/libpcrecpp.so
	PCRE3_VER=`ls $APP_LIB/libpcreposix.so.* |awk 'BEGIN{FS="libpcreposix.so."}{print $2}'`
	ln -sf $APP_LIB/libpcreposix.so.$PCRE3_VER $APP_LINK_LIB/libpcreposix.so.1
	ln -sf $APP_LIB/libpcreposix.so.$PCRE3_VER $APP_LINK_LIB/libpcreposix.so.0
	ln -sf $APP_LIB/libpcreposix.so.$PCRE3_VER $APP_LINK_LIB/libpcreposix.so

	killall -SIGTERM asus_lighttpd&
	sleep 3

	cd  /opt/bin
	./asus_lighttpd -Df /opt/etc/asus_lighttpd.conf&


    ;;
  stop)
	killall -SIGTERM asus_lighttpd&

    ;;

  lighttpd-restart)
	killall -SIGTERM asus_lighttpd&

	rm -rf /tmp/getdiskinfo_lock&
	rm -rf /tmp/APPS/DM2/Status/cgi_running&
	rm -rf /tmp/APPS/DM2/Config/dm2_general_protected &
	rm -rf /tmp/APPS/DM2/Config/dm2_detect_protected &
	rm -rf /tmp/APPS/Lighttpd/compress/downloadmaster &
	sleep 2
	cd /opt/bin && ./asus_lighttpd -Df /opt/etc/asus_lighttpd.conf &
    ;;

  firewall-start|firewall-restart)
	if [ -f "/tmp/asus_router.conf" ]; then
		LAN_IP_TMP=`cat "/tmp/asus_router.conf" | grep "LAN_IP" | awk 'BEGIN{FS="="} {print $2}'`
		if [ "$LAN_IP" != "$LAN_IP_TMP" ];then
			killall -SIGTERM asus_lighttpd&
			rm -rf /tmp/getdiskinfo_lock&
			rm -rf /tmp/APPS/DM2/Status/cgi_running&
			rm -rf /tmp/APPS/DM2/Config/dm2_general_protected &
			rm -rf /tmp/APPS/DM2/Config/dm2_detect_protected &
			rm -rf /tmp/APPS/Lighttpd/compress/downloadmaster&
			sleep 2
			killall -9 asus_lighttpd
			cd /opt/bin && ./asus_lighttpd -Df /opt/etc/asus_lighttpd.conf &
		fi
	fi
    ;;

  *)

    exit 1
    ;;
esac
