/*
** Copyright (c) 2009-2013 by Silicon Laboratories
**
** $Id: si_voice_version.c 3824 2013-02-05 16:46:08Z cdp $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "7.0.0";
