#
# Automatically generated make config: don't edit
#

#
# Library Configuration
#

#
# Force build (Normally built when required)
#
# CONFIG_LIB_LIBGMP_FORCE is not set
# CONFIG_LIB_LIBPTHREAD_FORCE is not set
CONFIG_LIB_LIBNVRAM_FORCE=y
# CONFIG_LIB_LIBNTFS3G_FORCE is not set
# CONFIG_LIB_LIBBT_FORCE is not set
# CONFIG_LIB_READLINE_FORCE is not set
# CONFIG_LIB_NL_FORCE is not set
# CONFIG_LIB_LIBPCAP_FORCE is not set
# CONFIG_LIB_LIBEVENT_FORCE is not set
# CONFIG_LIB_NCURSE_FORCE is not set
# CONFIG_LIB_FLEX_FORCE is not set
# CONFIG_LIB_LIBUPNP_FORCE is not set
# CONFIG_LIB_LIBUPNP166_FORCE is not set
# CONFIG_LIB_LIBUPNP166_DMS_FORCE is not set
# CONFIG_LIB_LIBDLNA_FORCE is not set
# CONFIG_LIB_LIBFFMPEG_FORCE is not set
# CONFIG_LIB_LIBGDBM_FORCE is not set
# CONFIG_LIB_LIBID3TAG_FORCE is not set
# CONFIG_LIB_LIBSQLITE3_FORCE is not set
# CONFIG_LIB_LIBEXIF_FORCE is not set
# CONFIG_LIB_LIBOGG_FORCE is not set
# CONFIG_LIB_LIBVORBIS_FORCE is not set
# CONFIG_LIB_LIBFLAC_FORCE is not set
# CONFIG_LIB_LIBJPEG_FORCE is not set
# CONFIG_LIB_LIBDB_FORCE is not set
# CONFIG_LIB_USB0112_FORCE is not set
# CONFIG_LIB_USB100_FORCE is not set
# CONFIG_LIB_PCRE_FORCE is not set
# CONFIG_LIB_VSTR_FORCE is not set
# CONFIG_LIB_ZLIB_FORCE is not set
# CONFIG_LIB_LZO_FORCE is not set
# CONFIG_LIB_E2FSPROGS_FORCE is not set
# CONFIG_LIB_LIBSTDC_PLUS_FORCE is not set
# CONFIG_USER_HELLO_WORLD is not set

#
# Force build extra libraries in uClibc
#
CONFIG_LIB_CRYPT_FORCE=y
CONFIG_LIB_LIBM_FORCE=y
# CONFIG_LIB_NSL_FORCE is not set
CONFIG_LIB_UTIL_FORCE=y
# CONFIG_LIB_RESOLV_FORCE is not set
# CONFIG_LIB_RT_FORCE is not set

#
# MTD utils
#
# CONFIG_USER_MTDUTILS is not set
# CONFIG_USER_MTDUTILS_DOCFDISK is not set
# CONFIG_USER_MTDUTILS_DOC_LOADBIOS is not set
# CONFIG_USER_MTDUTILS_FLASHCP is not set
# CONFIG_USER_MTDUTILS_FLASH_ERASE is not set
# CONFIG_USER_MTDUTILS_FLASH_ERASEALL is not set
# CONFIG_USER_MTDUTILS_FLASH_LOCK is not set
# CONFIG_USER_MTDUTILS_FLASH_OTP_DUMP is not set
# CONFIG_USER_MTDUTILS_FLASH_OTP_INFO is not set
# CONFIG_USER_MTDUTILS_FLASH_UNLOCK is not set
# CONFIG_USER_MTDUTILS_FTL_CHECK is not set
# CONFIG_USER_MTDUTILS_FTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_JFFS2DUMP is not set
# CONFIG_USER_MTDUTILS_JFFS2READER is not set
# CONFIG_USER_MTDUTILS_MKFSJFFS2 is not set
# CONFIG_USER_MTDUTILS_MTD_DEBUG is not set
# CONFIG_USER_MTDUTILS_NANDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDTEST is not set
# CONFIG_USER_MTDUTILS_NANDWRITE is not set
# CONFIG_USER_MTDUTILS_NFTLDUMP is not set
# CONFIG_USER_MTDUTILS_NFTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_RECV_IMAGE is not set
# CONFIG_USER_MTDUTILS_RFDDUMP is not set
# CONFIG_USER_MTDUTILS_RFDFORMAT is not set
# CONFIG_USER_MTDUTILS_SERVE_IMAGE is not set
# CONFIG_USER_MTDUTILS_SUMTOOL is not set
# CONFIG_USER_MTDUTILS_MKFSUBIFS is not set
# CONFIG_USER_MTDUTILS_MTDINFO is not set
# CONFIG_USER_MTDUTILS_UBIATTACH is not set
# CONFIG_USER_MTDUTILS_UBICRC32 is not set
# CONFIG_USER_MTDUTILS_UBIDETACH is not set
# CONFIG_USER_MTDUTILS_UBIFORMAT is not set
# CONFIG_USER_MTDUTILS_UBIMKVOL is not set
# CONFIG_USER_MTDUTILS_UBINFO is not set
# CONFIG_USER_MTDUTILS_UBINIZE is not set
# CONFIG_USER_MTDUTILS_UBIRENAME is not set
# CONFIG_USER_MTDUTILS_UBIRMVOL is not set
# CONFIG_USER_MTDUTILS_UBIRSVOL is not set
# CONFIG_USER_MTDUTILS_UBIUPDATEVOL is not set

#
# Network Applications
#
# CONFIG_USER_3G is not set
# CONFIG_USER_ACCEL_PPTP is not set
# CONFIG_USER_ARPTABLES is not set
# CONFIG_USER_BRCTL_BRCTL is not set
# CONFIG_USER_BIGPOND is not set
# CONFIG_USER_BT_UTILS is not set
# CONFIG_USER_BT_AVINFO is not set
# CONFIG_USER_BT_BCCMD is not set
# CONFIG_USER_BT_CIPTOOL is not set
# CONFIG_USER_BT_HCICONFIG is not set
# CONFIG_USER_BT_HCIATTACH is not set
# CONFIG_USER_BT_HCISECFILTER is not set
# CONFIG_USER_BT_HCITOOL is not set
# CONFIG_USER_BT_L2PING is not set
# CONFIG_USER_BT_PPPORC is not set
# CONFIG_USER_BT_SDPTOOL is not set
# CONFIG_USER_CTORRENT is not set
# CONFIG_USER_CPU is not set
# CONFIG_USER_DHCP6 is not set
# CONFIG_USER_DHCP6_SERVER is not set
# CONFIG_USER_DHCP6_CLIENT is not set
# CONFIG_USER_WIDE_DHCPV6 is not set
# CONFIG_USER_ISC_DHCP is not set
# CONFIG_USER_DROPBEAR is not set
# CONFIG_USER_DNSMASQ is not set
# CONFIG_USER_DISKTYPE is not set
# CONFIG_USER_ECHO_SERVER is not set
# CONFIG_USER_EBTABLES is not set
# CONFIG_USER_HOSTAPD is not set
# CONFIG_USER_STORAGE is not set
# CONFIG_USER_PROFTPD is not set
# CONFIG_USER_SAMBA is not set
# CONFIG_USER_GOAHEAD_HOSTNAME is not set
# CONFIG_USER_MKDOSFS is not set
# CONFIG_USER_MTDAAPD is not set
# CONFIG_USER_DNS_RESPONDER is not set
# CONFIG_USER_USHARE is not set
# CONFIG_USER_MINIDLNA is not set
# CONFIG_USER_DMS is not set
# CONFIG_LIB_LIBUPNP166_DMS_FORCE is not set
# CONFIG_USER_LIGHTY is not set
# CONFIG_USER_GOAHEAD_HTTPD is not set
# CONFIG_USER_GOAHEAD_IPV6 is not set
# CONFIG_USER_GOAHEAD_SSL is not set
# CONFIG_USER_GOAHEAD_HOSTNAME is not set
# CONFIG_USER_GOAHEAD_GreenAP is not set
# CONFIG_USER_WIZARD is not set
# CONFIG_USER_GOAHEAD_LANG_EN is not set
# CONFIG_USER_GOAHEAD_LANG_ZHTW is not set
# CONFIG_USER_GOAHEAD_LANG_ZHCN is not set
# CONFIG_USER_GOAHEAD_LANG_EN is not set
# CONFIG_USER_ECMH is not set
# CONFIG_USER_IGMP_PROXY is not set
# CONFIG_USER_INADYN is not set
# CONFIG_USER_IPTABLES_IPTABLES is not set
# CONFIG_USER_IPTABLES_IP6TABLES is not set
# CONFIG_USER_IPROUTE2 is not set
# CONFIG_USER_IPROUTE2_SS is not set
# CONFIG_USER_IPROUTE2_ARPD is not set
# CONFIG_USER_IPROUTE2_NSTAT is not set
# CONFIG_USER_IPROUTE2_IFSTAT is not set
# CONFIG_USER_IPROUTE2_RTACCT is not set
# CONFIG_USER_IPROUTE2_LNSTAT is not set
# CONFIG_USER_IPROUTE2_IP is not set
# CONFIG_USER_IPROUTE2_RTMON is not set
# CONFIG_USER_IPROUTE2_TC is not set
# CONFIG_USER_KAID is not set
# CONFIG_USER_MATRIXSSL is not set
# CONFIG_USER_MINIUPNPD is not set
# CONFIG_USER_NTPCLIENT_NTPCLIENT is not set
# CONFIG_USER_NTPCLIENT_ADJTIMEX is not set
# CONFIG_USER_OPENSSL is not set
# CONFIG_USER_OPENL2TP is not set
# CONFIG_USER_IPSEC_TOOLS is not set
# CONFIG_USER_OPENSWAN is not set
# CONFIG_USER_P910ND is not set
# CONFIG_USER_PARPROUTED is not set
# CONFIG_USER_PPPD is not set
# CONFIG_USER_PPPD_WITH_PPPOE is not set
# CONFIG_USER_PPPD_WITH_L2TP is not set
# CONFIG_USER_PPPD_WITH_PPTP is not set
# CONFIG_USER_PPPD_PPPSTATS is not set
# CONFIG_USER_PPPD_PPPDUMP is not set
# CONFIG_USER_PPPD_PPPCHAT is not set
# CONFIG_USER_RPPPPOE_RELAY is not set
# CONFIG_USER_RPPPPOE_SNIFF is not set
# CONFIG_USER_PPPOECD is not set
# CONFIG_USER_PPTP_CLIENT is not set
# CONFIG_USER_ZEBRA is not set
# CONFIG_LIB_LIBZEBRA_FORCE is not set
# CONFIG_USER_RP_L2TP is not set
# CONFIG_USER_RADVD is not set
# CONFIG_USER_RADVD_DUMP is not set
# CONFIG_USER_802_1X is not set
# CONFIG_USER_RT2561_802_1X is not set
# CONFIG_USER_SNORT is not set
# CONFIG_USER_SNMPD is not set
# CONFIG_USER_NETSNMP_SNMPD is not set
# CONFIG_USER_TOTD is not set
# CONFIG_USER_UVC_STREAM is not set
# CONFIG_USER_UPNP_IGD is not set
# CONFIG_USER_WPA_SUPPLICANT is not set
# CONFIG_USER_WSC is not set

#
# Wireless-tools
#
CONFIG_USER_WIRELESS_TOOLS=y
# CONFIG_USER_WIRELESS_TOOLS_IWCONFIG is not set
# CONFIG_USER_WIRELESS_TOOLS_IWGETID is not set
# CONFIG_USER_WIRELESS_TOOLS_IWLIST is not set
CONFIG_USER_WIRELESS_TOOLS_IWPRIV=y
# CONFIG_USER_WIRELESS_TOOLS_IWSPY is not set
# CONFIG_USER_WIRELESS_TOOLS_IWEVENT is not set

#
# Bluetooth-apps
#
# CONFIG_USER_BLUEANGEL is not set
# CONFIG_USER_BLUEANGEL_MTKBT is not set
# CONFIG_USER_BLUEANGEL_BTCLI is not set
# CONFIG_USER_BTCLI_ON is not set
# CONFIG_USER_BLUEANGEL_RELAYER is not set
# CONFIG_USER_BLUEANGEL_AUTOBT is not set
# CONFIG_BT_HCI_CMD is not set
# CONFIG_USER_ROUTER_PLAYER_NEW is not set

#
# Miscellaneous Applications
#
CONFIG_USER_BUSYBOX_BUSYBOX=y
# CONFIG_USER_BONNIE is not set
# CONFIG_USER_CACHEBENCH is not set
# CONFIG_USER_ETHTOOL is not set
# CONFIG_DHRYSTONE is not set
# CONFIG_DHCPFWD is not set
# CONFIG_USER_GDBREPLAY is not set
# CONFIG_USER_GDBSERVER is not set
# CONFIG_USER_IXIA_ENDPOINT is not set
# CONFIG_USER_IPERF is not set
# CONFIG_USER_I2C_TOOLS is not set
# CONFIG_USER_LMBENCH3 is not set
CONFIG_USER_MTD_WRITE=y
# CONFIG_USER_MPSTAT is not set
# CONFIG_USER_NBENCH is not set
# CONFIG_USER_NETCAT is not set
# CONFIG_USER_NETSTAT_NAT is not set
# CONFIG_USER_NTFS3G is not set
# CONFIG_USER_NTFSPROGS is not set
# CONFIG_LIB_LIBNTFS3G_FORCE is not set
# CONFIG_USER_STRACE_STRACE is not set
# CONFIG_USER_TCPDUMP is not set
# CONFIG_USER_TASKSET is not set
# CONFIG_USER_PCIUTIL_LSPCI is not set
# CONFIG_USER_PCIUTIL_SETPCI is not set
# CONFIG_USER_LSUSB is not set
# CONFIG_USER_USBMODESWITCH is not set
# CONFIG_USER_COMGT is not set
# CONFIG_USER_SDPARM is not set
# CONFIG_USER_WATCHDOG is not set
# CONFIG_USER_VMSTAT is not set
# CONFIG_USER_AIRPLAY is not set
# CONFIG_USER_FDK_AAC_ENCODER is not set

#
# Proprietary Application
#
CONFIG_RALINKAPP=y
CONFIG_RALINKAPP_ATED=y
CONFIG_RALINKAPP_REG_RW=y
# CONFIG_RALINKAPP_CSR is not set
CONFIG_RALINKAPP_FLASH=y
CONFIG_FLASH_TOOL=y
# CONFIG_ETHMAC_TOOL is not set
# CONFIG_RALINKAPP_HWNAT is not set
# CONFIG_RALINKAPP_SWNAT is not set
CONFIG_RALINKAPP_MII_MGR=y
CONFIG_RALINKAPP_NVRAM=y
CONFIG_LIB_LIBNVRAM_FORCE=y
# CONFIG_RALINKAPP_L2_MANAGE is not set
# CONFIG_RALINKAPP_GPIO is not set
# CONFIG_RALINKAPP_SPI is not set
# CONFIG_RALINKAPP_I2C is not set
# CONFIG_RALINKAPP_MEMORY_USAGE is not set
# CONFIG_USER_QOS is not set
# CONFIG_RALINKAPP_SWQOS is not set
# CONFIG_RALINKAPP_AUTO_WAN is not set
# CONFIG_RALINKAPP_SUPERDMZ is not set
CONFIG_RALINKAPP_SWITCH=y
CONFIG_RALINKAPP_LONG_LOOP=y
# CONFIG_RALINKAPP_I2S is not set
# CONFIG_RALINKAPP_PCM is not set
# CONFIG_RALINKAPP_SPDIF is not set
# CONFIG_RALINKAPP_PCIE_PHY is not set
# CONFIG_RALINKAPP_CLS is not set
# CONFIG_RALINKAPP_HOTSPOT is not set
# CONFIG_RALINKAPP_WAPI is not set
CONFIG_RALINKAPP_SCRIPTS=y
# CONFIG_RALINKAPP_BUSARB is not set
CONFIG_RALINKAPP_ETHPHY=y
# CONFIG_RALINKAPP_KPROFILE is not set
# CONFIG_UFSD_TOOL is not set
# CONFIG_UFSD_NTFS_TOOL is not set
# CONFIG_UFSD_HFS_TOOL is not set
# CONFIG_UFSD_EXFAT_TOOL is not set
# CONFIG_USER_NFCSD is not set
# CONFIG_USER_NFCHOD is not set
# CONFIG_USER_MET is not set
# CONFIG_USER_AB151X_TOOL is not set

#
# Windows Rally Program
#
# CONFIG_USER_LLTD is not set

#
# Phone Management
#
# CONFIG_MTK_VOIP is not set

#
# Remote Management
#
# CONFIG_MTK_TR069 is not set
