
#ifndef PROSLIC_TSTIN_LIMITS_H
#define PROSLIC_TSTIN_LIMITS_H


extern proslicPcmLpbkTest ProSLIC_testIn_PcmLpbk_Test;
extern proslicDcFeedTest ProSLIC_testIn_DcFeed_Test;
extern proslicRingingTest ProSLIC_testIn_Ringing_Test;
extern proslicBatteryTest ProSLIC_testIn_Battery_Test;
extern proslicAudioTest ProSLIC_testIn_Audio_Test;

#endif
