// JavaScript Document
var multiLanguage_all_array =new Array();
multiLanguage_all_array = [
						   [
							"Task",
							"Settings",
							"Language",
							"General",
							" ASUSTeK Computer Inc. All rights reserved.",
							"Proceeding",
							"Please wait...",
							"Complete!",
							"You have logged out successfully.",
							"User IP address:",
							"Another user needs to log out first so you can log in.",
							"Logout",
							"Are you sure you want to log out?",
							"Mobile",
							"Desktop",
							"English",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Username",
							"Password",
							"Sign in with your ASUS router account",
							"Sign in"
							],
						   [
							"任務",
							"設定",
							"語言",
							"一般設定",
							" 版權屬於 華碩電腦股份有限公司",
							"處理中",
							"請稍候,",
							"完成",
							"您已成功登出。",
							"已登入的使用者 IP:",
							"請先登出該名使用者後，再登入使用。",
							"登出",
							"確定要登出嗎？",
							"行動裝置",
							"桌上型電腦",
							"繁體中文",
							"DownloadMaster禁用",
							"DownloadMaster 不支持 Http",
							"帳號",
							"密碼",
							"用華碩路由器帳號登入",
							"登入"
							],
						   [
							"任务",
							"设置",
							"语言",
							"一般设置",
							" 版权属于 华硕电脑股份有限公司",
							"处理中",
							"请稍候,",
							"完成",
							"您已成功注销。",
							"已登录的用户IP:",
							"请先注销该名用户后，再登录使用。",
							"注销",
							"确定要注销吗？",
							"移动设备",
							"台式电脑",
							"简体中文",
							"DownloadMaster禁用",
							"DownloadMaster 不支持 Http",
							"帐号",
							"密码",
							"用华硕路由器帐号登录",
							"登录"
							],
						   [
							"Задача",
							"Настройки",
							"язык",
							"Общие<br />настройки",
							" ASUSTeK Computer Inc. Все права защищены",
							"Выполнение",
							"Подождите,",
							"Выполнено!",
							"Выход выполнен.",
							"IP пользователя:",
							"Вы не сможете войти, пока другой пользователь не выйдет.",
							"Выход",
							"Выйти?",
							"Мобильная версия",
							"Обычная версия",
							"Pусский",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Имя пользователя",
							"Пароль",
							"Войдите с помощью учетной записи роутера",
							"Войти"
							],
						   [
							"Tâche",
							"Préférences",
							"Langue",
							"Options<br />générales",
							"Copyright ©  ASUSTeK Computer Inc. Tous droits réservés",
							"Traitement en cours",
							"Veuillez patienter",
							"Terminé!",
							"Vous êtes déconnecté.",
							"Adresse IP de l'utilisateur connecté:",
							"Vous ne pouvez pas vous connecter sans déconnecter un autre utilisateur au préalable.",
							"Déconnexion",
							"Etes-vous sûr de vouloir vous déconnecter ?",
							"Version mobile",
							"Standard",
							"Français",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nom d'utilisateur",
							"Mot de passe",
							"Connexion à l'interface de gestion du routeur",
							"Connexion"
							],
						   [
							"Aufgabe",
							"Einstellungen",
							"Sprache",
							"Allgemeine<br />Einstellungen",
							" ASUSTek Computer Inc. Alle Rechte vorbehalten",
							"Fortfahren",
							"Bitte warten,",
							"Abgeschlossen!",
							"Sie haben sich erfolgreich abgemeldet.",
							"Anmelde-Benutzer-IP:",
							"Sie können sich erst nach der Abmeldung eines anderen Benutzers anmelden.",
							"Abmelden",
							"Mochten Sie sich wirklich abmelden?",
							"Mobil",
							"Desktop",
							"Deutsch",
							"Download Master deaktiviert",
							"Download Master unterstützt kein Http",
							"Benutzername",
							"Kennwort",
							"Mit Ihrem ASUS-Routerkonto anmelden",
							"Anmelden"
							],
						   [
							"Tarefa",
							"Configurações",
							"idioma",
							"Configuração<br />geral",
							" ASUSTeK Computer Inc.Todos os direitos reservados.",
							"Processando",
							"Por favor aguarde,",
							"Concluído !",
							"Você se desconectou com sucesso.",
							"Login do IP do usuário:",
							"Você não pode acessar sem ter saído do sistema anteriormente.",
							"Sair do sistema",
							"Você tem certeza que deseja sair do sistema ?",
							"Móvel",
							"Área de trabalho",
							"Portuguese(Brazil)&nbsp&nbsp&nbsp",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nome do usuário",
							"Senha",
							"Se registre com sua conta do roteador ASUS",
							"Registrar"
							],
						   [
							"Úkol",
							"Nastavení",
							"Jazyk",
							"Obecné<br />nastavení",
							" ASUSTeK Computer Inc. Všechna práva vyhrazena.",
							"Zpracovává se",
							"Prosím vyčkejte,",
							"Hotovo!",
							"Odhlášení proběhlo úspěšně.",
							"Login user IP:",
							"You cannot Login unless logout another user first.",
							"Odhlásit",
							"Opravdu se chcete odhlásit?",
							"Mobil",
							"Stolní počítač",
							"Česky",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Uživatelské jméno",
							"Heslo",
							"Přihlaste se k účtu vašeho ASUS směrovače",
							"Přihlásit"
							],
						   [
							"Opgave",
							"Indstillinger",
							"sprog",
							"Generelle<br />indstillinger",
							" ASUSTeK Computer Inc. Alle rettigheder forebeholdt.",
							"Fortsætter",
							"Vent et øjeblik,",
							"Fuldført!",
							"Du er logget korrekt af.",
							"Brugerens indlognings-IP:",
							"Du kan ikke logge på, med mindre en anden bruger logger af først.",
							"Log af",
							"Er du sikker på, at du ville logge af?",
							"Mobil",
							"Skrivebord",
							"Dansk",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Brugernavn",
							"Adgangskode",
							"Log på med kontoen til din ASUS router",
							"Log på"
							],
						   [
							"Tehtävä",
							"Asetukset",
							"kieli",
							"Yleinen asetus",
							" ASUSTeK Computer Inc. Kaikki oikeudet pidätetään.",
							"Jatketaan",
							"Odota,",
							"Valmis!",
							"Kirjautuminen ulos onnistui.",
							"Käyttäjän kirjautumis-IP:",
							"Et voi kirjautua sisään ennen kuin toinen käyttäjä kirjautuu ulos.",
							"Kirjaudu ulos",
							"Haluatko varmasti kirjautua ulos?",
							"Matkapuhelin",
							"Työpöytä",
							"Suomi",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Käyttäjänimi",
							"Salasana",
							"Kirjaudu sisään ASUS-reititin tililläsi.",
							"Kirjaudu sisään"
							],
						   [
							"Tugas",
							"Tetapan",
							"bahasa",
							"Tetapan Umum",
							" ASUSTeK Computer Inc. Hak cipta terpelihara.",
							"Meneruskan",
							"Sila tunggu,",
							"Selesai!",
							"Anda telah berjaya Log Keluar.",
							"Log masuk pengguna IP:",
							"Anda tidak boleh Log Masuk melainkan dengan melog keluar pengguna lain dahulu.",
							"Log keluar",
							"Adakah anda pasti hendak log keluar?",
							"Mudah Alih",
							"Desktop",
							"Malay",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nama pengguna",
							"Kata laluan",
							"Daftar masuk dengan akaun penghala ASUS anda",
							"Daftar masuk"
							],
						   [
							"Oppgave",
							"Innstillinger",
							"språk",
							"Generell<br />innstilling",
							" ASUSTek Computer Inc. Med enerett.",
							"Fortsetter",
							"Vent litt,",
							"Fullført!",
							"Du har logget ut.",
							"Bruker-IP for pålogging:",
							"Du kan ikke logge på med mindre en annen bruker først logger av.",
							"Logg av",
							"Er du sikker på at du vil logge av?",
							"Mobil",
							"Stasjonær PC",
							"Norsk",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Brukernavn",
							"Passord",
							"Logge på ASUS-ruterkontoen",
							"Logg på"
							],
						   [
							"Zadanie",
							"Ustawienia",
							"język",
							"Ustawienia<br />ogólne",
							" ASUSTeK Computer Inc. Wszelkie prawa zastrzeżone.",
							"Uaktualnianie...",
							"Proszę czekać,",
							"Zakończono!",
							"Wylogowałeś się",
							"Login user IP:",
							"Nie możesz się zalogować dopóki nie wylogujesz pozostałych użytkowników.",
							"Wyloguj",
							"Czy na pewno chcesz się wylogować?",
							"Przenośny",
							"Desktop",
							"Polski",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nazwa użytkownika",
							"Hasło",
							"Zaloguj się na konto swojego routera ASUS",
							"Zaloguj się"
							],
						   [
							"Uppgift",
							"Inställningar",
							"språk",
							"Allmän<br />inställning",
							" ASUSTeK Computer Inc. Alla rättigheter förbehållna.",
							"Går vidare",
							"Vänta,",
							"Avslutad!",
							"Du har loggat ut.",
							"IP för inloggad användare:",
							"Du kan inte logga in om inte en annan användare först loggar ut.",
							"Logga ut",
							"Är du säker på att du vill logga ut?",
							"Mobil",
							"Bordsdator",
							"Svensk",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Användarnamn",
							"Lösenord",
							"Logga in med ditt ASUS routerkonto",
							"Logga in"
							],
						   [
							"งาน",
							"การตั้งค่า",
							"ภาษา",
							"การตั้งค่าทั่วไป",
							" ASUSTeK Computer Inc. สงวนลิขสิทธิ์",
							"กำลังดำเนินการ",
							"โปรดรอสักครู่",
							"สมบูรณ์!",
							"คุณออกจากระบบสำเร็จแล้ว",
							"ผู้ใช้ล็อกอิน IP:",
							"คุณไม่สามารถล็อกอินได้ถ้าไม่ล็อกเอาต์ออกจากผู้ใช้อีกคนหนึ่งก่อน",
							"ล็อกเอาต์",
							"แน่ใจว่าต้องการล็อกเอาต์หรือไม่?",
							"มือถือ",
							"เดสก์ทอป",
							"ไทย",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"ชื่อผู้ใช้",
							"รหัสผ่าน",
							"ลงชื่อเข้าใช้ด้วยบัญชีเราเตอร์ ASUS ของคุณ",
							"ลงชื่อเข้าใช้"
							],
						   [
							"Görev",
							"Ayarlar",
							"dil",
							"Genel Ayar",
							" ASUSTeK Computer Inc. Tüm hakları saklıdır.",
							"İşlem Devam Ediyor",
							"Lütfen bekleyin,",
							"Tamamlandı!",
							"Oturumu başarıyla kapattınız.",
							"Oturum açma kullanıcı IP'si:",
							"Başka bir kullanıcı oturum kapatmadıkça Oturum Açamazsınız.",
							"Oturumu Kapat",
							"Oturumu kapattığınızdan emin misiniz?",
							"Mobil",
							"Masaüstü",
							"Türkçe",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Kullanıcı Adı",
							"Şifre",
							"ASUS yönlendirici hesabınızla oturum açın",
							"Oturum aç"
							],
						   [
							"タスク",
							"設定",
							"言語",
							"全般",
							" ASUSTek Computer Inc. All rights reserved.",
							"実行中...",
							"お待ちください...",
							"完了",
							"ログアウトしました。",
							"ログインユーザーIP:",
							"他のユーザーをログアウトしないとログインできません。",
							"ログアウト",
							"ログアウトしますか？",
							"モバイル",
							"デスクトップ",
							"日本語",
							"DownloadMaster 無効",
							"DownloadMaster はHTTPをサポートしません。",
							"ユーザー名",
							"パスワード",
							"ルーターの管理画面にアクセスするにはユーザー名とパスワードを入力してください",
							"ログイン"
							],
							[
							"Download",
							"Impostazioni",
							"lingua",
							"Generale",
							" ASUSTeK Computer Inc. All rights reserved.",
							"In corso...",
							"Attendere prego...",
							"Completato.",
							"Disconnessione eseguita con successo.",
							"Indirizzo IP dell'utente:",
							"Per eseguire l'accesso è necessario che un altro utente si disconnetta.",
							"Disconnetti",
							"Sei sicuro di volerti disconnettere?",
							"Mobile",
							"Desktop",
							"Italiano",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nome utente",
							"Password",
							"Accedi usando l'account del tuo router ASUS",
							"Accedi"
							],
							[
							"Feladat",
							"Beállítások...",
							"Nyelv",
							"Általános",
							" ASUSTeK Computer Inc. All rights reserved.",
							"Folyamatban…",
							"Kérjük, várjon...",
							"Kész.",
							"Sikeres kijelentkezés.",
							"Felhasználó IP-címe:",
							"Először egy másik felhasználónak ki kell jelentkeznie, hogy Ön be tudjon lépni.",
							"Kijelentkezés",
							"Biztos, hogy ki szeretne lépni?",
							"Mobil",
							"Asztali",
							"Hungarian",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Felhasználónév",
							"Jelszó",
							"Jelentkezzen be ASUS router-fiókjával",
							"Bejelentkezés"
							],
							[
							"Sarcină",
							"Setări",
							"limbă",
							"General",
							" ASUSTeK Computer Inc. All rights reserved.",
							"Se continuă...",
							"Aşteptaţi...",
							"Terminat.",
							"V-aţi deconectat cu succes.",
							"Adresă IP utilizator:",
							"Pentru ca dvs. să vă puteţi conecta este nevoie ca un alt utilizator să se deconecteze mai întâi.",
							"Deconectare",
							"Sigur doriţi să vă deconectaţi?",
							"Mobil",
							"Desktop",
							"Romanian",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nume utilizator",
							"Parolă",
							"Conectaţi-vă cu contul routerului ASUS",
							"Conectare"
							],
							[
							"Задача",
							"Налаштування",
							"мова",
							"Загальне",
							" ASUSTeK Computer Inc. All rights reserved.",
							"Обробка...",
							"Почекайте, будь ласка.",
							"Завершено",
							"Ви успішно вийшли з системи",
							"ІР-адреса користувача:",
							"Спочатку треба вийти іншому користувачеві, щоб ви могли увійти.",
							"Вийти",
							"Ви впевнені, що бажаєте вийти?",
							"Мобільний",
							"Стаціонарний комп'ютер",
							"Ukrainian",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Ім'я користувача",
							"Пароль",
							"Увійдіть до облікового запису маршрутизатора ASUS",
							"Вхід до системи"
							],
							[
							"Tarea",
							"Configuración",
							"idioma",
							"General",
							" ASUSTeK Computer Inc. All rights reserved.",
							"Procediendo...",
							"Espere...",
							"Completado.",
							"Ha cerrado sesión correctamente.",
							"Dirección IP del usuario:",
							"Para que usted pueda iniciar sesión, otro usuario debe cerrar la suya.",
							"Cerrar sesión",
							"¿Está seguro de que desea cerrar sesión?",
							"Móvil",
							"Equipo de sobremesa",
							"Español",
							"DownloadMaster Disabled",
							"DownloadMaster Not Support Http",
							"Nombre de usuario",
							"Contraseña",
							"Inicie sesión en la cuenta del router de ASUS",
							"Iniciar sesión"
							]
						   ]
