// JavaScript Document
var multiLanguage_array = new Array();
multiLanguage_array = [
	["Initializing torrent downloading process...",
		"Please wait a moment",
		"There are no completed tasks.",
		"Notice",
		"The URL is blank.",
		"The URL length must be less than 1024 characters.",
		"Please key in a URL or select a file.",
		"Please select the right file.",
		"Failed to delete the task.",
		"Failed to add the new download task.",
		"The task already exists.",
		"The http/ftp task list is full.",
		"The BT task list is full.",
		"The NZB task list is full.",
		"The task list is full.",
		"Are you sure you want to delete?",
		"Add a file or a URL to the download task list",
		"Please select a torrent or NZB file to upload",
		"File:",
		"Key in the HTTP, FTP, Magnet, ed2k, Torrent, or NZB URL",
		"Apply",
		"Cancel",
		"Add",
		"Remove",
		"Pause",
		"Resume",
		"Pause All",
		"Resume All",
		"Clear Completed Tasks",
		"Home",
		"Tasks",
		"All",
		"Downloading",
		"Seeding",
		"Paused",
		"Finished",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Destination:",
		"Creation time:",
		"File size:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Downloaded:",
		"Uploaded:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Speed:",
		"start time:",
		"time left:",
		"Log",
		"Tier",
		" Need Username or Password",
		" Check the hostname and port settings",
		" Make sure SSL is turned off",
		" Check the username and password",
		"Not enough disk space. Please delete some files to free some space in the USB storage device and click Resume to resume the download process.",
		"There is no scheduled download at this time.",
		"There is not enough space to store the file.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Please enter the Username and Password",
		"Username",
		"Password",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],
	["初始化 Torrent 下載中…",
		"請稍候",
		"沒有已完成任務。",
		"註：",
		"URL 為空。",
		"URL 的長度必須少於 1024 個字元。",
		"請輸入一個 URL 或選擇一個檔案。",
		"請選擇正確的檔案。",
		"移除任務失敗。",
		"新增新任務失敗。",
		"此任務已存在。",
		"http/ftp 任務清單已滿。",
		"BT 任務清單已滿。",
		"NZB 任務清單已滿。",
		"任務清單已滿。",
		"您確定要移除嗎？",
		"新增一個檔案或 URL 至下載任務清單",
		"請選擇一個要上傳的 Torrent 或 NZB 檔案",
		"檔案:",
		"輸入  HTTP、FTP、Magnet、ed2k、Torrent 或 NZB URL",
		"套用本頁面設定",
		"取消",
		"新增",
		"刪除",
		"暫停",
		"開始",
		"全部暫停",
		"全部開始",
		"清除已完成任務",
		"主頁",
		"傳送",
		"全部",
		"下載中",
		"上傳中",
		"已暫停",
		"已完成",
		"資訊",
		"片段:",
		"無用資訊:",
		"安全性:",
		"評論:",
		"已建立",
		"建立者:",
		"日期:",
		"位置",
		"下載目錄:",
		"目的地:",
		"建立時間:",
		"檔案大小:",
		"網址:",
		"活動",
		"過程:",
		"大小:",
		"狀態:",
		"可用性:",
		"已下載:",
		"已上傳:",
		"下載速度:",
		"上傳速度:",
		"錯誤:",
		"比率:",
		"連接數:",
		"上傳至:",
		"下載自:",
		"速度:",
		"開始時間:",
		"剩餘時間:",
		"記錄",
		"等級",
		" 需要使用者名稱與密碼",
		" 檢查主機名稱與埠設定。",
		" 確認 SSL 已關閉。",
		" 檢查使用者名稱與密碼",
		"磁碟空間不足。請移除一些檔案以釋放 USB 隨身碟儲存空間，接著點選 重新開始 重新進行下載。",
		"目前不是排定下載時段。",
		"儲存檔案的空間不足。",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"磁碟格式為FAT32，該格式不支持大於4G的檔案。<br>請更換磁碟格式，以完成下載。<br>NTFS ext4 ext3等格式支持大於4G的檔案。",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"請輸入使用者名稱與密碼",
		"使用者名稱",
		"密碼",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT任務不可被暫停，其他任務將會被暫停",
		"Please check the aMule server status"
	],

	["正在初始化 Torrent 下载…",
		"请稍候",
		"没有已完成任务。",
		"注：",
		"URL 为空。",
		"URL 的长度必须少于 1024 个字符。",
		"请输入一个 URL 或选择一个文件。",
		"请选择正确的文件。",
		"删除任务失败。",
		"添加新任务失败。",
		"此任务已存在。",
		"http/ftp 任务列表已满。",
		"BT 任务列表已满。",
		"NZB 任务列表已满。",
		"任务列表已满。",
		"您确定要删除吗？",
		"添加一个文件或 URL 至下载任务列表",
		"请选择一个要上传的 Torrent 或 NZB 文件",
		"文件:",
		"输入 HTTP、FTP、Magnet、ed2k、Torrent 或 NZB URL",
		"应用本页面设置",
		"取消",
		"新增",
		"刪除",
		"暂停",
		"开始",
		"全部暂停",
		"全部开始",
		"清除已完成任务",
		"主页",
		"发送",
		"全部",
		"正在下载",
		"上传中",
		"已暂停",
		"已完成",
		"信息",
		"片段:",
		"无用信息:",
		"安全性:",
		"评论:",
		"已创建",
		"创建者:",
		"日期:",
		"位置",
		"下载目录:",
		"目的地:",
		"创建时间:",
		"文件大小:",
		"网址:",
		"活动",
		"过程:",
		"大小:",
		"状态:",
		"可用性:",
		"已下载:",
		"已上传:",
		"下载速度:",
		"上传速度:",
		"错误:",
		"比率:",
		"连接数:",
		"上传至:",
		"下载自:",
		"速度:",
		"开始时间:",
		"剩余时间:",
		"记录",
		"等级",
		" 需要用户名与密码",
		" 检查主机名与端口设置。",
		" 确认 SSL 已关闭。",
		" 检查用户名与密码",
		"磁盘空间不足。请删除一些文件以释放 USB 闪存盘储存空间，然后点击【重新开始】重新进行下载。",
		"目前不是排定下载时段。",
		"存储文件的空间不足。",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"磁盘格式为FAT32，该格式不支持大于4G的文件。<br>请更换磁盘格式，以完成下载。<br>NTFS ext4 ext3 等格式支持大于4G的文件。",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"请输入用户名与密码",
		"用户名",
		"密码",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT任务不可被暂停，其他任务将会被暂停",
		" 请检查aMule 服务器状态"
	],

	["Инициализация процесса загрузки торрента..",
		"Пожалуйста, подождите",
		"Нет завершенных загрузок",
		"Обратите внимание",
		"URL пуст",
		"Длина URL должна быть не менее 1024 символов",
		"Пожалуйста, введите URL или выберите файл",
		"Пожалуйста, выберите правильный файл",

		"Не удалось удалить задачу",
		"Ошибка при добавлении новой загрузки.",
		"Задача уже существует",
		"Список задач http/ftp заполнен",
		"Список задач BT заполнен",
		"Список задач NZB заполнен",
		"Список задач заполнен",
		"Вы хотите удалить?",
		"Добавить файл или URL в список загрузок",
		"Выберите для загрузки файл torrent или NZB",
		"Файл:",
		"Введите URL для HTTP, FTP, Magnet, ed2k, Torrent или NZB",
		"Применить",
		"Отмена",
		"Добавить",
		"Удалить",
		"Пауза",
		"Возобновить",
		"Приостановить все",
		"Возобновить все",
		"Очистить завершенные загрузки",
		"Главный экран",
		"Передано",
		"Все",
		"Загрузка",
		"Раздача",
		"Приостановлена",
		"Завершена",
		"Информация",
		"Части:",
		"Хэш:",
		"Безопасность:",
		"Комментарий:",
		"Создано",
		"Создатель:",
		"Дата:",
		"Где",
		"Директория для загрузки:",
		"Назначение:",
		"Время создания:",
		"Размер файла:",
		"URL:",
		"Активность",
		"прогресс:",
		"размер:",
		"статус:",
		"доступность:",
		"Загружено:",
		"Отдано:",
		"Скорость загрузки:",
		"Скорость отдачи:",
		"Ошибка:",
		"Показатель:",
		"Загружающий:",
		"Загрузить на:",
		"Скачать с:",
		"Скорость:",
		"время начала:",
		"оставшееся время:",
		"Журнал",
		"Ряд",
		" Необходимы имя пользователя или пароль",
		" Проверьте настройки имени хоста и порта.",
		" Убедитесь, что SSL отключен.",
		" Проверьте имя пользователя и пароль",
		"Недостаточно места на диске. Для  освобождения места на USB-накопителе удалите некоторые файлы и нажмите Возобновить для возобновления процесса загрузки.",
		"В это время нет запланированной загрузки.",
		"Недостаточно места для хранения файла.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Пожалуйста, введите имя пользователя и пароль",
		"Имя пользователя",
		"Пароль",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Initialisation du processus de téléchargement de torrent…",
		"Veuillez patienter un instant",
		"Aucune tâche terminée.",
		"Remarque :",
		"Le champ réservé à l'URL est vide",
		"La longueur de l'URL ne doit pas dépasser 1024 caractères",
		"Veuillez entrer une URL ou sélectionner un fichier.",
		"Veuillez sélectionner le bon fichier.",
		"Échec de suppression de la tâche.",
		"Échec d'ajout de la nouvelle tâche de téléchargement.",
		"Cette tâche existe déjà.",
		"La liste des tâches HTTP/FTP est pleine.",
		"La liste des tâches BT est pleine.",
		"La liste des tâches NZB est pleine.",
		"La liste des tâches est pleine.",
		"Souhaitez-vous vraiment supprimer ce(s) fichier(s) ?",
		"Ajouter une tâche ou une URL à télécharger",
		"Veuillez sélectionner un fichier Torrent ou NZB à transmettre",
		"Fichier:",
		"Veuillez entrer l'URL du fichier HTTP, FTP, Magnet, ed2k, Torrent ou NZB",
		"Appliquer",
		"Annuler",
		"Ajouter une tâche",
		"Supprimer",
		"Pause",
		"Démarrer",
		"Suspendre tout",
		"Démarrer tout",
		"Effacer les tâches terminées",
		"Accueil",
		"Transferts",
		"Tout",
		"En cours",
		"Seeding",
		"Suspendu",
		"Terminé",
		"Informations",
		"Pièces:",
		"Hash:",
		"Sécurité:",
		"Commentaires:",
		"Créé par",
		"Auteur:",
		"Date:",
		"Emplacement",
		"Répertoire:",
		"Destination:",
		"Date de création:",
		"Taille:",
		"URL:",
		"Activité",
		"Progression:",
		"Taille:",
		"État:",
		"Disponibilité:",
		"Téléchargé:",
		"Transmis:",
		"Vitesse de téléchargement:",
		"Vitesse de transmission:",
		"Erreur:",
		"Ratio:",
		"Peers:",
		"Transmettre vers:",
		"Télécharger de:",
		"Vitesse:",
		"Début:",
		"Temps restant:",
		"Journal",
		"Niveau",
		" Nom d'utilisateur et mot de passe requis",
		" Vérifiez le nom d'hôte et le port.",
		" Assurez-vous que le protocole SSL est désactivé.",
		" Vérifiez le nom d'utilisateur et le mot de passe.",
		"Espace disque insuffisant. Veuillez libérer de l'espace de stockage sur votre dispositif USB avant de relancer le processus de téléchargement.",
		"Aucun téléchargement planifié disponible.",
		"L'espace disque est insuffisant pour stocker le fichier.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Veuillez entrer votre nom d'utilisateur et mot de passe",
		"Nom d'utilisateur",
		"Mot de passe",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Torrent-Download-Prozess wird initialisiert...",
		"Bitte einen Moment warten",
		"Keine fertigen Aufgaben verfügbar.",
		"Hinweis:",
		"Die URL ist leer.",
		"Die URL darf nicht länger als 1024 Zeichen sein.",
		"Bitte geben Sie eine URL ein oder wählen Sie eine Datei aus.",
		"Bitte die richtige Datei auswählen.",
		"Löschen der Aufgabe fehlgeschlagen",
		"Hinzufügen einer neuen Download-Aufgabe fehlgeschlagen.",
		"Die Aufgabe existiert schon.",
		"Die HTTP/FTP-Aufgabenliste ist voll.",
		"Die BT-Aufgabenliste ist voll.",
		"Die NZB-Aufgabenliste ist voll.",
		"Die Aufgabenliste ist voll.",
		"Wollen Sie diese wirklich löschen?",
		"Datei oder URL zur Download-Aufgabenliste hinzufügen.",
		"Bitte Torrent- oder NZB-Datei für das Hochkladen auswählen.",
		"Datei:",
		"Geben Sie die HTTP-, FTP-, Magnet-, ed2k-, Torrent- oder NZB-URL ein.",
		"Anwenden",
		"Abbrechen",
		"Aufgabe hinzufügen",
		"Löschen",
		"Pause",
		"Start",
		"Alle pausieren",
		"Alle starten",
		"Fertige Aufgaben löschen",
		"Home",
		"Übertragungen",
		"Alle",
		"Herunterladen",
		"Seeden",
		"Pausiert",
		"Beendet",
		"Informationen",
		"Teile:",
		"Hash:",
		"Sichern:",
		"Kommentar:",
		"Erstellt",
		"Urheber:",
		"Datum:",
		"Wo",
		"Download-Verzeichnis:",
		"Ziel:",
		"Erstellungszeit:",
		"Dateigröße:",
		"URL:",
		"Aktivität",
		"Fortschritt:",
		"Größe:",
		"Status:",
		"Verfügbarkeit:",
		"Heruntergeladen:",
		"Hochgeladen:",
		"Download-Geschwindigkeit:",
		"Uplooad-Geschwindigkeit:",
		"Fehler:",
		"Verhältnis:",
		"Peers:",
		"Hochladen zu:",
		"Herunterladen von:",
		"Geschwindigkeit:",
		"Startzeit:",
		"verbleibende Zei:",
		"Protokoll",
		"Ebene",
		" Benutzername oder Kennwort benötigt",
		" Überprüfen Sie den Host-Namen und die Port-Einstellungen.",
		" Vergewissern Sie sich, dass SSL ausgeschaltet ist.",
		" Überprüfen Sie Benutzername und Kennwort",
		"Nicht genügend freier Festplattenspeicher vorhanden. Löschen Sie bitte nicht benötigte Dateien, um Speicherplatz in Ihrem USB-Datenträger frei zu machen und klicken Sie auf Wieder aufnehmen, um den Download fortzuführen.",
		"Zu dieser Zeit ist kein Download geplant.",
		"Zu wenig Platz zum Speichern der Datei.",
		"Die Datenblöcke der Datei sind nicht vollständig",
		"Datenträger ist voll",
		"Das Datenträgerformat ist FAT32, welches keine Dateien unterstützt, die größer als 4 GB sind. Bitte wechseln Sie das Datenträgerformat, um den Download abzuschließen.<br>NTFS, ext4, ext3 und andere Formate unterstützen Dateien, die größer als 4 GB sind.",
		"Der Download-Datenträger kann keine Dateien unterstützen, die größer als 4 GB sind. Deshalb wird die Datei im Ordner 'Download2/Incomplete' gespeichert.",
		"Bitte Benutzername und Kennwort eingeben",
		"Benutzername",
		"Kennwort",
		"Das Format wird nicht unterstützt",
		"Der Download-Datenträger ist voll. Deshalb wird die Datei im Ordner 'Download2/Incomplete' gespeichert.",
		"Die BT-Aufgabe kann nicht angehalten werden, andere Aufgaben werden angehalten",
		"Bitte überprüfen Sie den aMule Serverstatus"
	],

	["Inicializando o processo de download de torrent...",
		"Por favor, aguarde um momento",
		"Não há tarefas completas.",
		"Aviso",
		"O URL está em branco.",
		"O URL não pode conter menos do que 1024 ",
		"Digite um URL ou selecione um arquivo.",
		"Seleciona o arquivo correto.",
		"Falha ao excluir a tarefa.",
		"Falha ao adicionar a nova tarefa de download.",
		"A tarefa já existe.",
		"A lista de tarefa http/ftp está cheia.",
		"A lista de tarefa BT está cheia.",
		"A lista de tarefa NZB está cheia.",
		"A lista de tarefa está cheia.",
		"Tem certeza de que deseja excluir?",
		"Adicionar um arquivo ou URL à lista de tarefa de download",
		"Selecione um arquivo torrent ou NZB para upload.",
		"Arquivo:",
		"Digite o URL do HTTP, FTP, Magnet, ed2k, Torrent, ou NZB",
		"Aplicar",
		"Cancelar",
		"Adicionar",
		"Remover",
		"Pausa",
		"Continuar",
		"Pausar tudo",
		"Resumir tudo",
		"Limpar tarefas completas",
		"Início",
		"Transferências",
		"Todos",
		"Fazendo Download",
		"Servindo",
		"Pausado",
		"Finalizado",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Destino:",
		"Hora de criação:",
		"Tamanho de arquivo:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Baixado:",
		"Carregado:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Velocidade:",
		"hora de início:",
		"tempo restante:",
		"Registro",
		"Tier",
		" Necessário nome de usuário ou senha",
		" Verifique as configurações de nome de host e porta.",
		" Certifique-se que o SSL está desligado.",
		" Verifique o nome de usuário e senha",
		"Sem espaço suficiente em disco Por favor, apague alguns arquivos para liberar espaço no dispositivo de armazenamento USB e clique em Resume (Continuar) para retomar o processo de download.",
		"Não há download programado neste momento.",
		"Não há espaço suficiente para armazenar o arquivo.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Por favor insira o nome de usuário e senha",
		"Nome do usuário",
		"Senha",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Inicializace procesu stahování souborů torrent...",
		"Okamžik vyčkejte",
		"Nejsou k dispozici žádné dokončené úkoly.",
		"Oznámení",
		"Adresa URL je prázdná.",
		"Délka adresu URL musí být méně než 1024 znaků.",
		"Zadejte adresu URL nebo vyberte soubor.",
		"Vyberte správný soubor.",
		"Odstranění úkolu se nezdařilo.",
		"Přidání nové úlohy stahování se nezdařilo.",
		"Tento úkol již existuje.",
		"Seznam úkolů http/ftp je plný.",
		"Seznam úkolů BT je plný.",
		"Seznam úkolů NZB je plný.",
		"Seznam úkolů je plný.",
		"Opravdu chcete odstranit?",
		"Přidat soubor nebo adresu URL do seznamu úkolů stahování",
		"Vyberte soubor torrent nebo NZB k odeslání",
		"Soubor:",
		"Zadejte HTTP, FTP, Magnet, ed2k, Torrent nebo NZB URL",
		"Použít",
		"Storno",
		"Přidat",
		"Odstranit",
		"Pozastavit",
		"Obnovit",
		"Pozastavit vše",
		"Obnovit vše",
		"Vymazat dokončené úkoly",
		"Domů",
		"Přenosy",
		"Vše",
		"Stahování",
		"Ohlašování",
		"Pozastaveno",
		"Dokončeno",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Místo určení:",
		"Čas vytvoření:",
		"velikost souboru.:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Staženo:",
		"Odesláno:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Rychlost:",
		"počáteční čas:",
		"zbývající čas:",
		"Protokol",
		"Tier",
		" Je zapotřebí uživatelské jméno nebo heslo",
		" Zkontrolujte název hostitele a nastavení portů.",
		" Zkontrolujte, zda je SSL vypnuto.",
		" Zkontrolujte uživatelské jméno a heslo",
		"Nedostatek místa na disku. Odstraněním některých souborů uvolněte místo v paměťovém zařízení USB a klepnutím na Resume (Pokračovat) pokračujte v procesu stahování.",
		"Na tento čas není naplánováno žádné stahování.",
		"Nedostatek místa k uložení souboru.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Zadejte uživatelské jméno nebo heslo",
		"Uživatelské jméno",
		"Password (Heslo)",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Initialiserer downloadproces for torrent…",
		"Vent et øjeblik",
		"Der er ingen afsluttede opgaver.",
		"Bemærk",
		"URL-en er tom.",
		"URL'en skal være kortere end 1.024 tegn.",
		"Indtast en URL eller vælg en fil.",
		"Vælg den rigtige fil.",
		"Kunne ikke slette opgaven.",
		"Kunne ikke tilføje den nye download-opgave.",
		"Opgaven findes allerede.",
		"Http/ftp opgavelisten er fyldt.",
		"Bt opgavelisten er fyldt.",
		"NZB opgavelisten er fyldt.",
		"Opgavelisten er fyldt.",
		"Er du sikker på, du vil slette?",
		"Tilføj en fil eller en URL til opgavelisten for download.",
		"Vælg en torrent- eller NZB-fil til upload",
		"Fil:",
		"Indtast HTTP, FTP, Magnet, ed2k, Torrent eller NZB URL",
		"Anvend",
		"Annuller",
		"Tilføj",
		"Fjern",
		"Pause",
		"Genoptag",
		"Sæt alle på pause",
		"Genoptag alle",
		"Ryd afsluttede opgaver",
		"Retur",
		"Overførsler",
		"Alle",
		"Downloader",
		"Seeder",
		"Sat på pause",
		"Afsluttet",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Destination:",
		"Oprettet kl.:",
		"Filstørrelse:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Downloaded:",
		"Uploaded:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Hastighed:",
		"Starttidspunkt:",
		"Resterende tid:",
		"Log",
		"Tier",
		" Du skal bruge et brugernavn og en adgangskode",
		" Kontroller værtsnavnet og portindstillingerne.",
		" Sørg for, at SSL er slukket.",
		" Kontroller dit brugernavn og adgangskode",
		"Ikke nok diskplads. Slet venligst nogle filer, så du har plads på din USB-lagringsenhed, og klik herefter på Resume (Genoptag), for at genoptage download-processen.",
		"Der er ikke nogen planlagt download på dette tidspunkt.",
		"Der er ikke nok plads til at gemme filen.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Indtast venligst dit brugernavn og adgangskode",
		"Brugernavn",
		"Adgangskode",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Alustetaan torrentin latausprosessia...",
		"Odota hetki",
		"Valmiita tehtäviä ei ole.",
		"Huomaa",
		"URL on tyhjä.",
		"URL-pituuden on oltava alle 1024 merkkiä.",
		"Näppäile kenttään URL tai valitse tiedosto.",
		"Valitse oikea tiedosto.",
		"Tehtävän poistaminen epäonnistui.",
		"Uuden lataustehtävän lisääminen epäonnistui.",
		"Tehtävä on jo olemassa.",
		"http/ftp-tehtäväluettelo on täynnä.",
		"BT-tehtäväluettelo on täynnä.",
		"NZB-tehtäväluettelo on täynnä.",
		"Tehtäväluettelo on täynnä.",
		"Haluatko varmasti poistaa?",
		"Lisää tiedosto tai URL lataustehtäväluetteloon",
		"Valitse lähetettävä torrentti tai NZB-tiedosto",
		"Tiedosto:",
		"Näppäile HTTP-, FTP-, Magnet-, ed2k-, Torrent-, tai NZB-URL-osoite",
		"Käytä",
		"Peruuta",
		"Lisää tehtävä",
		"Poista",
		"Keskeytä",
		"Käynnistä",
		"Keskeytä kaikki",
		"Käynnistä kaikki",
		"Tyhjennä valmiit tehtävät",
		"Aloitusnäyttö",
		"Siirtää",
		"Kaikki",
		"Ladataan",
		"Alustus",
		"Keskeytetty",
		"Valmis",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Kohde:",
		"Luontiaika:",
		"Tiedostokoko:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Ladatut:",
		"Lähetetyt:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Nopeus:",
		"alkamisaika:",
		"aikaa jäljellä:",
		"Loki",
		"Tier",
		" Tarvitaan käyttäjätunnus tai salasana",
		" Tarkista isäntänimi ja porttiasetukset.",
		" Varmista, että SSL on kytketty pois päältä.",
		" Tarkista käyttäjänimi ja salasana",
		"Levytila ei riitä. Vapauta hieman levytilaa USB-tallennuslaitteesta poistamalla joitakin tiedostoja ja jatka lataamista napsauttamalla Resume (Jatka)-painiketta.",
		"Tällä ajalla ei ole aikataulun mukaista latausta.",
		"Tila ei riitä tiedoston tallentamiseen.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Anna käyttäjätunnus ja salasana.",
		"Käyttäjänimi",
		"Salasana",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Memulakan proses muat turun torrent...",
		"Sila tunggu sebentar",
		"Tiada tugas yang telah selesai.",
		"Notis",
		"URL kosong.",
		"Panjang URL mesti kurang daripada 1024 aksara.",
		"Sila masukkan URL atau pilih fail.",
		"Sila pilih fail yang betul.",
		"Gagal untuk memadamkan tugas.",
		"Gagal untuk menambah tugasan muat turun yang baru.",
		"Tugas telah wujud.",
		"Senarai tugas http/ftp penuh.",
		"Senarai tugas BT penuh.",
		"Senarai tugas NZB penuh.",
		"Senarai tugas penuh.",
		"Anda pasti hendak memadamkan?",
		"Tambah fail atau URL pada senarai tugas muat turun",
		"Sila pilih fail torrent atau NZB untuk memuat naik",
		"Fail:",
		"Masukkan URL HTTP, FTP, Magnet, ed2k, Torrent, atau NZB",
		"Gunakan",
		"Batal",
		"Tambah",
		"Keluarkan",
		"Jeda",
		"Sambung",
		"Jeda Semua",
		"Sambung Semua",
		"Kosongkan Tugas yang Telah Selesai",
		"Rumah",
		"Pemindahan",
		"Semua",
		"Memuat turun",
		"Pembenihan",
		"Dijeda",
		"Selesai",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Destinasi:",
		"Masa penciptaan:",
		"Saiz fail:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Dimuat turun:",
		"Dimuat naik:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Kelajuan:",
		"masa bermula:",
		"masa yang tinggal:",
		"Log",
		"Tier",
		" Memerlukan Nama Pengguna atau Kata Laluan",
		" Periksa nama hos dan tetapan port.",
		" Pastikan SSL dimatikan.",
		" Periksa nama pengguna dan kata laluan",
		"Ruang cakera tidak mencukupi. Sila pada beberapa fail untuk mengosongkan sedikit ruang pada peranti storan USB dan klik Resume (Sambung Semula) untuk menyambung semula proses muat turun.",
		"Tiada muat turun yang dijadualkan kali ini.",
		"Ruang tidak mencukupi untuk menyimpan fail.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Sila masukkan Nama Pengguna dan Kata Laluan",
		"Nama pengguna",
		"Kata laluan",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Initialiserer torrent-nedlastningsprosess …",
		"Vent et øyeblikk",
		"Det finnes ingen fullførte oppgaver.",
		"Merknad",
		"URL-en er tom.",
		"URL-lengden må være mindre enn 1024 tegn.",
		"Tast inn en URL eller velg en fil.",
		"Velg riktig fil.",
		"Kunne ikke slette oppgaven.",
		"Kunne ikke legge til den nye nedlastingsoppgaven.",
		"Oppgaven finnes allerede.",
		"Http/ftp-oppgavelisten er full.",

		"BT-oppgavelisten er full.",
		"NZB-oppgavelisten er full.",
		"Oppgavelisten er full.",
		"Er du sikker på at du vil slette?",
		"Legg til en fil eller en URL til nedlastningsoppgavelisten",
		"Velg en torrent- eller NZB-fil for opplastning",
		"Fil:",
		"Tast inn HTTP, FTP, Magnet, ed2k, Torrent eller NZB URL",
		"Bruk",
		"Avbryt",
		"Legg til",
		"Fjern",
		"Pause",
		"Gjenoppta",
		"Pause alle",
		"Gjenoppta alle",
		"Fjern fullførte oppgaver",
		"Hjem",
		"Overføringer",
		"Alle",
		"Laster ned",
		"Seeding",
		"Pauset",
		"Fullført",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Destinasjon:",
		"Opprettet tidspunkt:",
		"Filstørrelse:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Nedlastet:",
		"Lastet opp:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Hastighet:",
		"starttid:",
		"gjenværende tid:",
		"Logg",
		"Tier",
		" Behov for brukernavn og passord",
		" Velg vertsnavnet og portinnstillinger",
		" Sørg for at SSL er slått av",
		" Kontroller brukernavnet og passordet",
		"Ikke nok diskplass. Slett noen filer for å frigjøre plass på USB-lagringsenheten og klikk på Resume (Fortsett) for å fortsette nedlastingsprosessen.",
		"Det er ingen planlagt nedlasting for øyeblikket.",
		"Det er ikke nok plass til å lagre filen.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Skriv inn brukernavnet og passordet",
		"Brukernavn",
		"Passord",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Inicjalizacja procesu pobierania torrent...",
		"Proszę chwilę poczekać",
		"Brak zakończonych zadań.",
		"Uwaga",
		"Adres URL jest pusty.",
		"Długość adresu URL musi być krótsza niż 1024 znaków.",
		"Wpisz adres URL lub wybierz plik.",
		"Wybierz poprawny plik.",
		"Niepowodzenie usunięcia zadania.",
		"Nie powiodło się dodanie nowego zadania pobierania.",
		"Zadanie już istnieje.",
		"Lista zadań http/ftp pełna.",
		"Lista zadań BT pełna.",
		"Lista zadań NZB pełna.",
		"Lista zadań pełna.",
		"Czy jesteś pewien, że chcesz usunąć?",
		"Dodaj plik lub adres URL do listy zadań pobierania",
		"Wybierz plik torrent lub NZB do przesłania",
		"Plik:",
		"Wpisz adres URL HTTP, FTP, ed2k, Magnet, Torrent lub NZB",
		"Zastosuj",
		"Anuluj",
		"Dodaj",
		"Usuń",
		"Pauza",
		"Wznów",
		"Wstrzymaj wszystkie",
		"Wznów wszystkie",
		"Usuń zakończone zadania",
		"Strona główna",
		"Transfery",
		"Wszystkie",
		"Pobieranie",
		"Udostępnianie",
		"Wstrzymane",
		"Zakończone",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Przeznaczenie:",
		"Czas utworzenia:",
		"Rozmiar pliku:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Pobrane:",
		"Przesłane:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Szybkość:",
		"czas uruchomienia:",
		"miniony czas:",
		"Dziennik",
		"Tier",
		" Wymagana nazwa użytkownika lub hasło",
		" Sprawdź nazwę hosta i ustawienia portu.",
		" Upewnij się, że jest wyłączone SSL.",
		" Sprawdź nazwę użytkownika i hasło",
		"Za mało miejsca na dysku. Usuń część plików, aby zwolnić trochę miejsca w urządzeniu pamięci masowej USB i kliknij Resume (Wznów), aby wznowić proces pobierania.",
		"Brak w tej chwili pobrań wynikających z harmonogramu.",
		"Za mało miejsca, aby zapisać plik.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Wprowadź nazwę użytkownika i hasło",
		"Nazwa użytkownika",
		"Hasło",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Initierar nedladdning av torrent...",
		"Vänta ett ögonblick",
		"Det finns inga slutförda uppgifter.",
		"Obs",
		"Webbadressen är tom.",
		"Längden på webbadressen måste vara mindre än 1024 tecken.",
		"Knappa in en webbadress eller välj en fil.",
		"Välj rätt fil",
		"Det gick inte att ta bort uppgiften.",
		"Misslyckades att lägga till den nya nedladdningsuppgiften",
		"Uppgiften finns redan.",
		"Uppgiftslistan http/ftp är full.",
		"Uppgiftslistan BT är full.",
		"Uppgiftslistan NZB är full.",
		"Uppgiftslistan är full.",
		"Är du säker på att du vill ta bort?",
		"Lägg till en fil eller en webbadress i listan över nedladdade uppgifter.",
		"Välj en torrent eller NZB fil att ladda upp",
		"Fil:",
		"Knappa in HTTP, FTP, Magnet, ed2k, Torrent eller NZB webbadressen",
		"Tillämpa",
		"Avbryt",
		"Lägg till uppgift",
		"Ta bort",
		"Paus",
		"Fortsätt",
		"Pausa alla",
		"Fortsätt alla",
		"Rensa slutförda uppgifter",
		"Hem",
		"Överföringar",
		"Alla",
		"Laddar ner",
		"Seeding",
		"Pausat",
		"Slut",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Destination:",
		"Skapandetid:",
		"Filstorlek:",
		"Webbadress:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"Nedladdade:",
		"Uppladdade:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Hastighet:",
		"starttid:",
		"tid kvar:",
		"Logg",
		"Tier",
		" Behöver användarnamn och lösenord",
		" Kontrollera värdnamnet och portinställningarna.",
		" Se till att SSL är avstängd",
		" Kontrollera användarnamnet och lösenordet",
		"Inte tillräckligt med diskutrymme. Radera några filer för att frigöra utrymme på USB-lagringsenheten och klicka på Resume (Återuppta) för att återuppta nedladdningsprocessen.",
		"Det finns ingen schemalagd nedladdning vid denna tidpunkt.",
		"Det finns inte tillräckligt med utrymme för att spara filen.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Ange användarnamnet och lösenordet",
		"Användarnamn",
		"Lösenord",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["กำลังตั้งค่าเริ่มต้นกระบวนการดาวน์โหลดทอร์เร้นต์...",
		"โปรดรอสักครู่",
		"ไม่มีงานที่สมบูรณ์",
		"ข้อสังเกต",
		"URL ว่าง",
		"ความยาว URL ต้องน้อยกว่า 1024 ตัวอักษร",
		"โปรดป้อน URL หรือเลือกไฟล์",
		"โปรดเลือกไฟล์ที่ถูกต้อง",
		"ไม่สามารถลบงาน",
		"ไม่สามารถเพิ่มงานดาวน์โหลดใหม่ได้",
		"งานมีอยู่แล้ว",
		"รายงานงาน http/ftp เต็ม",
		"รายงานงาน BT เต็ม",
		"รายงานงาน NZB เต็ม",
		"รายงานงานเต็ม",
		"แน่ใจว่าต้องการลบหรือไม่?",
		"เพิ่มไฟล์หรือ URL เพื่อดาวน์โหลดรายการงาน",
		"โปรดเลือกไฟล์ทอร์เร้นต์หรือไฟล์ NZB เพื่ออัปโหลด",
		"ไฟล์:",
		"ป้อน HTTP, FTP, Magnet, Torrent หรือ NZB URL",
		"นำไปใช้",
		"ยกเลิก",
		"เพิ่ม",
		"ลบ",
		"หยุดชั่วคราว",
		"ดำเนินการต่อ",
		"หยุดชั่วคราวทั้งหมด",
		"ดำเนินการต่อทั้งหมด",
		"ล้างงานที่สมบูรณ์แล้ว",
		"โฮม",
		"ถ่ายโอน",
		"ทั้งหมด",
		"กำลังดาวน์โหลด",
		"กำลังสีด",
		"หยุดชั่วคราว",
		"เสร็จแล้ว",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"ปลายทาง:",
		"เวลาสร้าง:",
		"ขนาดไฟล์:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"ดาวน์โหลดแล้ว:",
		"อัปโหลดแล้ว:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"ความเร็ว:",
		"เวลาเริ่ม:",
		"เวลาที่เหลือ:",
		"บันทึก",
		"Tier",
		" จำเป็นต้องมีชื่อผู้ใช้หรือรหัสผ่าน",
		" ตรวจสอบชื่อโฮสต์และการตั้งค่าพอร์ต ",
		" ตรวจดูให้แน่ใจว่า SSL ปิด",
		" ตรวจสอบชื่อผู้ใช้และรหัสผ่าน",
		"พื้นที่ว่างบนดิสก์ไม่เพียงพอ โปรดลบบางไฟล์ เพื่อปลดปล่อยพื้นที่ในอุปกรณ์เก็บข้อมูล USB และคลิก Resume (ทำต่อ) เพื่อดำเนินกระบวนการดาวน์โหลดต่อ",
		"ไม่มีกำหนดการดาวน์โหลด ณ เวลานี้",
		"มีพื้นที่บนดิสก์ไม่เพียงพอที่จะเก็บไฟล์.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"โปรดป้อนชื่อผู้ใช้และรหัสผ่าน",
		"ชื่อผู้ใช้",
		"รหัสผ่าน",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],

	["Torrent indirme işlemini başlatıyor...",
		"Lütfen bir an bekleyin",
		"Tamamlanan görev yok.",
		"Uyarı",
		"URL boş.",
		"URL uzunluğu 1024 karakterden kısa olmalıdır.",
		"Lütfen bir URL girin veya bir dosya seçin.",
		"Lütfen doğru dosyayı seçin.",
		"Görevi silinemedi.",
		"Yeni indirme görevi eklenemedi.",
		"Görev zaten mevcut.",
		"http/ftp görev listesi dolu.",
		"BT görev listesi dolu.",
		"NZB görev listesi dolu.",
		"Görev listesi dolu.",
		"Silmek istediğinizden emin misiniz?",
		"İndirme görev listesine bir dosya veya URL ekleyin",
		"Lütfen bir torrent veya NZB dosyası seçerek yükleyin",
		"Dosya:",
		"HTTP, FTP, Magnet, ed2k, Torrent veya NZB URL girin",
		"Uygula",
		"İptal",
		"Ekle",
		"Kaldır",
		"Duraklat",
		"Devam Et",
		"Tümünü Duraklat",
		"Tümünü Devam Ettir",
		"Tamamlanan Görevleri Temizle",
		"Ana Sayfa",
		"Aktarımlar",
		"Tümü",
		"İndiriliyor",
		"Köklüyor",
		"Duraklatıldı",
		"Bitti",
		"Information",
		"Pieces:",
		"Hash:",
		"Secure:",
		"Comment:",
		"Created",
		"Creator:",
		"Date:",
		"Where",
		"Download Directory:",
		"Hedef:",
		"Oluşturma saati:",
		"Dosya boyutu:",
		"URL:",
		"Activity",
		"progress:",
		"size:",
		"status:",
		"availability:",
		"İndirildi:",
		"Yüklendi:",
		"Download Speed:",
		"Upload Speed:",
		"Error:",
		"Ratio:",
		"Peers:",
		"Upload to:",
		"Download from:",
		"Hız:",
		"başlangıç saati:",
		"kalan süre:",
		"Günlük",
		"Tier",
		" Kullanıcı Adı veya Parola gereklidir",
		" Ana makine adını ve bağlantı noktası ayarlarını kontrol edin.",
		" SSL’nin kapatıldığından emin olun.",
		" Kullanıcı adını ve parolayı kontrol edin",
		"Yeterli disk alanı yok. USB bellek aracında boş alan açmak için lütfen bazı dosyaları silin ve indirme işlemini yeniden başlatmak için Resume (Devam ettir) öğesine tıklayın.",
		"Halihazırda programlanmış bir indirme görevi yok.",
		"Dosyayı saklamak için yeterli alan yok.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Lütfen Kullanıcı Adını ve Parolayı girin",
		"Kullanıcı Adı",
		"Parola",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],
	[
		"Torrentダウンロードの初期化中... ",
		"しばらくお待ちください",
		"完了したタスクはありません。",
		"注意",
		"URLフィールドは空欄です。.",
		" URLは1,024文字以内で指定してください。",
		"URLを入力するか、ファイルを選択してください。",
		"正しいファイルを選択してください。",
		"タスクの削除に失敗しました。",
		"失敗するタスクを追加.",
		"タスクは既に存在します",
		"http/ftp タスクの上限数を超えています。",
		"BT タスクの上限数を超えています。",
		"NZB タスクの上限数を超えています。",
		"タスクの上限数を超えています。",
		"削除しますか？",
		"ダウンロードタスクリストにファイルまたはURLを追加",
		"アップロードするtorrent またはNZB ファイルを選択してください。",
		"ファイル:",
		"Key in the HTTP, FTP, Magnet, ed2k, Torrent, or NZB URL",
		"適用",
		"キャンセル",
		"追加",
		"削除",
		"休止",
		"一時停止",
		"すべて一時停止",
		"すべてレジューム",
		"完了したタスクを削除",
		"ホーム",
		"タスク",
		"すべて",
		"ダウンロード中",
		"シード中",
		"一時停止",
		"完了",
		"設定情報",
		"データ:",
		"ハッシュ:",
		"セキュリティ:",
		"コメント:",
		"作成済み",
		"作成者:",
		"日付:",
		"場所",
		"ダウンロードディレクトリ:",
		"目的地:",
		"作成時間:",
		"ファイルサイズ:",
		"URL:",
		"アクティビティ",
		"進行状況:",
		"サイズ:",
		"状態:",
		"可用性:",
		"ダウンロード済み:",
		"アップロード済み:",
		"ダウンロード速度:",
		"アップロード速度:",
		"エラー:",
		"負担率:",
		"ピア:",
		"アップロード中のピア数:",
		"ダウンロード中のピア数:",
		"速度:",
		"開始時間:",
		"残り時間:",
		"ログ",
		"階層",
		" ユーザー名とパスワードが必要です。",
		" ホスト名とポートの設定を確認します。",
		" SSLがオフになっていることを確認します。",
		" ユーザー名とパスワードを確認します。",
		"ディスクの空き容量が不足しています。USBストレージデバイスの不要なファイルを削除し、「レジューム」をクリックし、再度ダウンロードを行います。",
		"現在ダウンロードスケジュールは設定されていません。",
		"ディスクに十分な空き領域がありません。",
		"ファイルのデータブロックが完全ではありません",
		"空き容量なし",
		"FAT32のディスクフォーマットは、4GBを超えるファイルをサポートしていません。<br>ダウンロードを完了するには、ディスクフォーマットを変更してください。NTFS、EXT4、EXT3および他のフォーマットでは4G以上のファイルをサポートします。",
		"ダウンロード先のディスクは4GB以上のファイルをサポートしていないため、Download2/Incompleteフォルダーに保存しました。",
		"ユーザー名とパスワードを入力してください。",
		"ユーザー名",
		"パスワード",
		"サポート外のファイルフォーマットです。",
		"ダウンロード先のディスクがいっぱいのため、Download2/Incompleteフォルダーに保存しました。",
		"BTのタスクを一時停止することはできません。他のタスクは一時停止されます。",
		"aMuleサーバーの状態を確認してください。"
	],
	[
		"Preparazione del download torrent in corso...",
		"Attendere prego",
		"Non ci sono processi completati.",
		"Conferma",
		"L'URL non esiste.",
		"L'URL deve essere più corto di 1024 caratteri.",
		"Inserite un URL o selezionate un file.",
		"Selezionate il file corretto.",
		"Eliminazione del processo non riuscita.",
		"Errore mentre si tentava di aggiungere il nuovo download alla coda dei download.",
		"Il processo esiste già.",
		"L'elenco dei processi http/ftp è pieno.",
		"L'elenco dei processi Torrent è pieno.",
		"L'elenco dei processi NZB è pieno.",
		"L'elenco dei processi è pieno.",
		"Siete sicuri di voler eliminare il download?",
		"Aggiungi un file o un collegamento all'elenco dei download",
		"Selezionate un file torrent o NBZ da caricare.",
		"File:",
		"Inserite il collegamento HTTP, FTP, Magnet, ed2k, Torrent o NZB",
		"Applica",
		"Annulla",
		"Aggiungi",
		"Rimuovi",
		"Pausa",
		"Riprendi",
		"Metti tutti in pausa",
		"Ferma tutti",
		"Elimina i download completati",
		"Home",
		"Download",
		"Tutto",
		"In download",
		"In seed",
		"In pausa",
		"Terminati",
		"Informazioni",
		"Parti",
		"Hash",
		"Sicuro",
		"Commenti",
		"Aggiunto il",
		"Aggiunto da",
		"Data",
		"Dove",
		"Percorso di download",
		"Destinazione",
		"Creato il",
		"Dimensione file",
		"URL",
		"Dettagli",
		"Progresso",
		"Dimensione",
		"Stato",
		"Orario",
		"Scaricato con successo",
		"Caricato con successo",
		"Velocità download",
		"Velocità upload",
		"Errori",
		"Rapporto",
		"Fonti",
		"Upload a",
		"Download da",
		"Velocità",
		"Iniziato il",
		"Tempo residuo",
		"Registro",
		"Livello",
		"Necessari Nome Utente e Password",
		" Controllate il nome dell'host e le impostazioni della porta.",
		" Assicuratevi che SSL sia disattivato.",
		" Controllate nome utente e password",
		"Spazio su disco non sufficiente. Cancellate alcuni file per liberare spazio sul disco USB e cliccate su Resume per riavviare il download.",
		"Nessun download pianificato al momento.",
		"Non c'è spazio sufficiente per salvare il file.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Inserite Nome Utente e Password",
		"Nome Utente",
		"Password",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],
	[
		"A torrent-letöltési folyamat inicializálása...",
		"Kérjük, várjon egy pillanatot",
		"Nincs befejezett feladat.",
		"Megerősítés",
		"Az URL-cím üres.",
		"Az URL-címnek 1024 karakternél rövidebbnek kell lennie.",
		"Kérjük, adjon meg egy URL-címet, vagy válasszon ki egy fájlt.",
		"Kérjük, válassza ki a helyes fájlt.",
		"A feladat törlése sikertelen.",
		"Az új letöltési feladat hozzáadása sikertelen volt.",
		"A feladat már létezik.",
		"A http/ftp feladatok listája megtelt.",
		"A BT-feladatok listája megtelt.",
		"Az NZB-feladatok listája megtelt.",
		"A feladatlista megtelt.",
		"Biztos, hogy törölni szeretné?",
		"Fájl vagy URL-cím hozzáadása a letöltési feladatok listájához",
		"Kérjük, válasszon ki egy torrent- vagy NZB-fájlt a feltöltéshez.",
		"Fájl:",
		"Adja meg a HTTP, FTP, Magnet, ed2k, Torrent vagy NZB URL-címét.",
		"Alkalmazás",
		"Mégse",
		"Hozzáadás",
		"Eltávolítás",
		"Szünet",
		"Folytatás",
		"Mind szüneteltetése",
		"Mind folytatása",
		"Kész feladatok törlése",
		"Kezdőoldal",
		"Feladatok",
		"Mind",
		"Letöltés",
		"Küldés",
		"Szüneteltetve",
		"Befejezve",
		"Információk",
		"Darabok",
		"Kivonat",
		"Biztonságos",
		"Megjegyzés",
		"Létrehozva",
		"Létrehozta:",
		"Dátum",
		"Hely",
		"Letöltési könyvtár",
		"Célhely",
		"Létrehozás időpontja",
		"Fájlméret",
		"URL",
		"Tevékenység",
		"Folyamat állapota",
		"Méret",
		"Állapot",
		"Rendelkezésre állás",
		"Letöltve",
		"Feltöltve",
		"Letöltési sebesség",
		"Feltöltési sebesség",
		"Hiba",
		"Arány",
		"Partnerek",
		"Feltöltés ide:",
		"Letöltés innen:",
		"Sebesség",
		"Kezdési időpont",
		"Hátralévő idő",
		"Napló",
		"Szint",
		" Felhasználónév vagy jelszó szükséges",
		" Ellenőrizze az állomásnevet és a portbeállításokat.",
		" Győződjön meg róla, hogy az SSL funkció ki van kapcsolva.",
		" Ellenőrizze a felhasználónevet és a jelszót",
		"Nincs elég hely a lemezen. Kérjük, hogy töröljön néhány fájlt az USB háttértárról, és kattintson a Folytatás gombra a letöltési folyamat folytatásához.",
		"Nincs ütemezett letöltés beállítva erre az időpontra.",
		"Nincs elegendő tárhely a fájl tárolásához.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Kérjük, hogy adja meg a felhasználónevet és jelszót",
		"Felhasználónév",
		"Jelszó",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],
	[
		"Se iniţializează procesul de descărcare a torentului...",
		"Aşteptaţi câteva momente",
		"Nu există sarcini finalizate",
		"Confirmare",
		"Nu s-a introdus nimic pentru adresa URL.",
		"Adresa URL trebuie să conţină mai puţin de 1.024 de caractere.",
		"Introduceţi o adresă URL sau selectaţi un fişier.",
		"Selectaţi fişierul corect.",
		"Nu s-a putut şterge sarcina.",
		"Nu s-a putut adăuga noua sarcină de descărcare.",
		"Sarcina există deja.",
		"Lista de sarcini HTTP/FTP este plină.",
		"Lista de sarcini BT este plină.",
		"Lista de sarcini NZB este plină.",
		"Lista de sarcini este plină.",
		"Sigur doriţi să ştergeţi?",
		"Adăugaţi un fişier sau o adresă URL la lista cu sarcini de descărcare",
		"Selectaţi un fişier torent sau NZB pentru a-l încărca.",
		"Fişier:",
		"Introduceţi adresa URL pentru protocolul HTTP sau FTP sau ed2k ori pentru fişierul magnet, Torent sau NZB.",
		"Aplicare",
		"Anulare",
		"Adăugare",
		"Eliminare",
		"Întrerupere",
		"Reluare",
		"Întrerupere toate",
		"Reluare toate",
		"Ştergere sarcini finalizate",
		"Acasă",
		"Sarcini",
		"Toate",
		"În descărcare",
		"În seeding",
		"Întrerupte",
		"Terminate",
		"Informaţii",
		"Bucăţi",
		"Cod hash",
		"Securizat",
		"Comentariu",
		"Creat",
		"Creator",
		"Dată",
		"Locaţie",
		"Director descărcare",
		"Destinaţie",
		"Oră creare",
		"Dimensiune fişier",
		"URL",
		"Activitate",
		"Evoluţie",
		"Dimensiune",
		"Stare",
		"Disponibilitate",
		"Descărcat",
		"Încărcat",
		"Viteză descărcare",
		"Viteză încărcare",
		"Eroare",
		"Raport",
		"Perechi",
		"Încărcare către",
		"Descărcare de la",
		"Viteză",
		"oră începere",
		"timp rămas",
		"Jurnal",
		"Nivel",
		" Sunt necesare numele de utilizator şi parola",
		" Verificaţi setările pentru numele gazdei şi port.",
		" Asiguraţi-vă că funcţionalitatea SSL este dezactivată.",
		" Verificaţi numele de utilizator şi parola.",
		"Spaţiu insuficient pe disc. Ştergeţi unele fişiere pentru a elibera spaţiu pe dispozitivul de stocare USB şi apoi faceţi clic pe Resume (Reluare) pentru a relua procesul de descărcare.",
		"Nu există nicio descărcare programată în acest moment.",
		"Nu există suficient spaţiu pentru stocarea fişierului.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Introduceţi numele de utilizator şi parola",
		"Nume utilizator",
		"Parolă",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],
	[
		"Початок процесу завантаження з торента...",
		"Будь ласка, трохи почекайте",
		"Нема завершених задач.",
		"Підтвердження",
		"URL порожня.",
		"Довжина URL мусить не перевершувати 1024 знаків.",
		"Будь ласка, введіть URL або виберіть файл.",
		"Будь ласка, виберіть правильний час.",
		"Не видалено задачу.",
		"Не додане нове завдання завантаження",
		"Задача вже існує.",
		"Список задач http/ftp повний.",
		"Список задач ВТ повний.",
		"Список задач NZB повний.",
		"Список задач повний.",
		"Ви впевнені, що бажаєте видалити?",
		"Додайте файл або URL, щоб завантажити список задач",
		"Будь ласка, виберіть торент або файл NZB для завантаження.",
		"Файл:",
		"Введіть HTTP, FTP, ed2k, Magnet, Torrent або NZB URL",
		"Застосувати",
		"Скасувати",
		"Додати",
		"Зняти",
		"Пауза",
		"Відновити",
		"Пауза всього",
		"Відновити все",
		"Очистити виконані задачі",
		"Головна",
		"Задачі",
		"Все",
		"Завантаження",
		"Роздача файлів",
		"На паузі",
		"Закінчено",
		"Інформація",
		"Частини",
		"Гешування",
		"Безпечно",
		"Коментар",
		"Створено",
		"Автор",
		"Дата",
		"Де",
		"Директорія завантажень",
		"Місце призначення",
		"Час створення",
		"Розмір файлу",
		"URL",
		"Дія",
		"Поступ",
		"Розмір",
		"Статус",
		"Доступність",
		"Завантажено",
		"Вивантажено",
		"Швидкість завантаження",
		"Швидкість вивантаження",
		"Помилка",
		"Пропорція",
		"Рівноправні учасники",
		"Вивантажити в",
		"Завантажити з",
		"Швидкість",
		"час початку",
		"часу лишилося",
		"Обліковий запис",
		"Рівень",
		" Потрібні ім'я користувача або пароль",
		" Перевірте назву хоста і налаштування порта",
		" Переконайтеся, що вимкнено SSL",
		" Перевірте ім'я користувача і пароль",
		"Недостатньо місця на диску. Будь ласка, видаліть декілька файлів, щоб звільнити місце в пам'яті USB, і клацніть Resume (Відновити), щоб продовжити процес завантаження.",
		"На цей час не призначено завантажень",
		"Недостатньо місця для збереження файла.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Будь ласка, введіть ім'я користувача і пароль",
		"Ім'я користувача",
		"Пароль",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	],
	[
		"Inicializando el proceso de descarga torrent...",
		"Espere un momento.",
		"No hay tareas completadas.",
		"Confirmación",
		"La dirección URL está en blanco.",
		"La dirección URL debe tener menos de 1.024 caracteres.",
		"Escriba una dirección URL o seleccione un archivo.",
		"Seleccione el archivo correcto.",
		"No se pudo eliminar la tarea.",
		"No se pudo agregar la nueva tarea de descarga.",
		"La tarea ya existe.",
		"La lista de tareas http/ftp está completa.",
		"La lista de tareas BT está completa.",
		"La lista de tareas NZB está completa.",
		"La lista de tareas está completa.",
		"¿Está seguro de que desea realizar la eliminación?",
		"Agregar un archivo o una dirección URL a la lista de tareas de descarga",
		"Seleccione un archivo Torrent o NZB para cargar.",
		"Archivo:",
		"Escriba la dirección URL HTTP, FTP, ed2k, Magnet, Torrent o NZB URL",
		"Aplicar",
		"Cancelar",
		"Agregar",
		"Quitar",
		"Pausar",
		"Reanudar",
		"Pausar todo",
		"Reanudar todo",
		"Borrar tareas completadas",
		"Inicio",
		"Tareas",
		"Todo",
		"Descargar",
		"Copia",
		"En pausa",
		"Finalizado",
		"Información",
		"Partes",
		"Hash",
		"Segura",
		"Comentario",
		"Creado",
		"Autor",
		"Fecha",
		"Dónde",
		"Directorio de descarga",
		"Destino",
		"Fecha y hora de creación",
		"Tamaño de archivo",
		"Dirección URL",
		"Actividad",
		"Progreso",
		"Tamaño",
		"Estado",
		"Disponibilidad",
		"Descargado",
		"Cargado",
		"Velocidad de descarga",
		"Velocidad de carga",
		"Error",
		"Relación",
		"Pares",
		"Cargar a",
		"Descargar de",
		"Velocidad",
		"hora de inicio",
		"tiempo restante",
		"Registro",
		"Nivel",
		" Se necesita un nombre de usuario o contraseña",
		" Compruebe la configuración del nombre de host y del puerto.",
		" Asegúrese de que SSL está desactivado.",
		" Compruebe el nombre de usuario y la contraseña.",
		"Espacio en disco insuficiente. Elimine algunos archivos para liberar algo de espacio en el dispositivo de almacenamiento USB y haga clic en Resume (Reanudar) para reanudar el proceso de descarga.",
		"No hay una descarga programada a esta hora.",
		"No hay espacio suficiente para almacenar el archivo.",
		"The file\'s data blocks are not complete",
		"Diskfull",
		"The disk format is FAT32, which does not support files larger than 4G. <br>Please replace the disk format to complete the download. <br>NTFS ext4 ext3 and other formats support files larger than 4G.",
		"Download disk cannot support more than 4GB file,so we put it in Download2/Incomplete folder",
		"Introduzca el nombre de usuario y la contraseña.",
		"Nombre de usuario",
		"Contraseña",
		"Format is not supported",
		"Download disk is full,so we put it in Download2/Incomplete folder",
		"BT task cannot be paused, other tasks will be paused",
		"Please check the aMule server status"
	]
];
