export SRCBASE := $(shell pwd)
BUILD := $(shell (gcc -dumpmachine))
HOSTCC := gcc
PLATFORM := mipsel-uclibc
CROSS_COMPILE := mipsel-linux-
CONFIGURE := ./configure --host=mipsel-linux --build=$(BUILD)
export TOOLCHAIN := $(shell cd $(dir $(shell which $(CROSS_COMPILE)gcc))/.. && pwd)
export IPKG_TOOLS := $(shell cd $(dir $(shell which $(CROSS_COMPILE)gcc))/../../../ipkg-utils-1.7 && pwd)
export LD_DIR := $(TOOLCHAIN)

export CC := $(CROSS_COMPILE)gcc
export AR := $(CROSS_COMPILE)ar
export AS := $(CROSS_COMPILE)as
export LD := $(CROSS_COMPILE)ld
export NM := $(CROSS_COMPILE)nm
export RANLIB := $(CROSS_COMPILE)ranlib
export STRIP := $(CROSS_COMPILE)strip
export SIZE := $(CROSS_COMPILE)size
export CXX := $(CROSS_COMPILE)g++
# libpasswd:
export LDFLAGS_P := -L$(TOOLCHAIN)/lib -lcrypt -Wl,-rpath,/opt/lib   
export	CFLAGS_P := -Os -Wall  -fPIC	
#
# standard packages
#
obj-y += mkdir
obj-y += DM-UI
obj-y += CGI
obj-y += dm2_detect
obj-y += snarf
obj-y += zlib
obj-y += libpng
obj-y += pcre
obj-y += libxml2
obj-y += sqlite
obj-y += openssl
obj-y += nzbget
obj-y += libevent
obj-y += libcurl
obj-y += libpasswd
obj-y += nvram-encrypt
obj-y += transmission-2.92
obj-y += readline
obj-y += expat
obj-y += wxbase
obj-y += crypto
obj-y += amule
obj-y += DownloadMaster-ipk
obj-y += openssl-ipk
obj-y += libcurl-ipk

all: $(obj-y)

clean:libpasswd-clean nvram-encrypt-clean

	-@$(MAKE) -C CGI2.1 clean
	-rm dm2_detect/stamp-h2
	-@$(MAKE) -C dm2_detect clean
	-@$(MAKE) -C snarf-7.0 clean
	-rm zlib/stamp-h2
	-@$(MAKE) -C zlib clean
	-@$(MAKE) -C libpng clean
	-@$(MAKE) -C pcre clean
	-@$(MAKE) -C libxml2 clean
	-@$(MAKE) -C sqlite-3.7.3 clean
	-@$(MAKE) -C openssl clean
	-@$(MAKE) -C nzbget-0.7.0 clean
	-@$(MAKE) -C libevent clean
	-rm libevent/stamp-h2
	-@$(MAKE) -C libcurl clean
	-@$(MAKE) -C transmission-2.92 clean
	-@$(MAKE) -C readline clean
	-@$(MAKE) -C expat clean
	-rm wxbase/stamp-h2
	-@$(MAKE) -C wxbase clean
	-@$(MAKE) -C crypto++ clean
	-@$(MAKE) -C amuled clean


distclean:clean
	rm -rf DownloadMaster-ipk-2.1/opt/etc/downloadmaster/downloadmaster/*
	rm -rf DownloadMaster-ipk-2.1/opt/tmp/bin/*
	rm -rf $(SRCBASE)/DownloadMaster-ipk-2.1/opt/etc/init.d/S50downloadmaster
	rm -rf $(SRCBASE)/DownloadMaster-ipk-2.1/CONTROL/control
	rm -rf openssl-ipk-2.1/opt/tmp/share/openssl/*
	rm -rf openssl-ipk-2.1/opt/tmp/lib/*
	rm -rf $(SRCBASE)/openssl-ipk-2.1/CONTROL/control
	rm -rf $(SRCBASE)/libcurl-ipk-2.1/CONTROL/control
	rm -rf $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/bin/*
	rm -rf $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/lib/*
	
mkdir:
	-mkdir -p openssl-ipk-2.1/opt/tmp/bin/
	-mkdir -p openssl-ipk-2.1/opt/tmp/lib/
	-mkdir -p DownloadMaster-ipk-2.1/opt/etc/downloadmaster/downloadmaster
	-mkdir -p DownloadMaster-ipk-2.1/opt/tmp/bin/
	-mkdir -p openssl-ipk-2.1/opt/tmp/share/openssl/
	-mkdir -p libcurl-ipk-2.1/opt/tmp/bin/
	-mkdir -p libcurl-ipk-2.1/opt/tmp/lib/
	-mkdir -p DownloadMaster-ipk-2.1/opt/etc/init.d/

DM-UI:
	rm -rf DownloadMaster-ipk-2.1/opt/etc/downloadmaster/downloadmaster
	cp -rf downloadmaster-UI DownloadMaster-ipk-2.1/opt/etc/downloadmaster/downloadmaster

CGI2.1/stamp-h2:
	cd CGI2.1 && \
	touch stamp-h2;

CGI:CGI2.1/stamp-h2
	@$(MAKE) -C CGI2.1 clean
	@$(MAKE) -C CGI2.1 all
	$(STRIP) CGI2.1/*.cgi
	cp -rf CGI2.1/*.cgi DownloadMaster-ipk-2.1/opt/etc/downloadmaster/downloadmaster/
	
dm2_detect/stamp-h2:
	cd dm2_detect && \
	touch stamp-h2;

dm2_detect:dm2_detect/stamp-h2	
	@$(MAKE) -C dm2_detect all
	$(STRIP) dm2_detect/dm2_detect
	cp -rf dm2_detect/dm2_detect DownloadMaster-ipk-2.1/opt/tmp/bin/

snarf/stamp-h2:
	cd  snarf-7.0 && \
	touch stamp-h2;

snarf:snarf/stamp-h2
	@$(MAKE) -C snarf-7.0 all
	$(STRIP) snarf-7.0/dm2_snarf
	$(STRIP) snarf-7.0/dm2_snarfmaster
	cp -rf snarf-7.0/dm2_snarf DownloadMaster-ipk-2.1/opt/tmp/bin/dm2_snarf
	cp -rf snarf-7.0/dm2_snarfmaster DownloadMaster-ipk-2.1/opt/tmp/bin/dm2_snarfmaster

zlib/stamp-h2:
	cd zlib && \
	touch stamp-h2;

zlib:zlib/stamp-h2
	cd zlib && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		prefix=$(SRCBASE)/opt \
		./configure \
		--shared
	@$(MAKE) -C  zlib all
	cd zlib && \
	$(MAKE) install
	
libpng/stamp-h2:
	cd libpng &&\
	touch stamp-h2

.PHONY: libpng/stamp-h2

libpng:libpng/stamp-h2
	cd libpng && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		CPPFLAGS="-O2   -pipe  -I$(SRCBASE)/opt/include " \
		LDFLAGS=" -L$(SRCBASE)/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib " \
		./configure \
		--build=i386-pc-linux-gnu \
		--host=mipsel-linux \
		--target=mipsel-linux \
		--prefix=$(SRCBASE)/opt \
		--disable-nls \
		--disable-static
	@$(MAKE) -C  libpng all
	cd libpng && \
	$(MAKE) install
	
pcre/stamp-h2:
	cd pcre &&\
	touch stamp-h2

pcre:pcre/stamp-h2
	cd pcre && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --prefix=$(SRCBASE)/opt --host=mips-linux 
	@$(MAKE) -C  pcre all 
	cd pcre && \
	$(MAKE) install

libxml2/stamp-h2:
	cd libxml2 &&\
	touch stamp-h2;

.PHONY: libxml2/stamp-h2

libxml2:libxml2/stamp-h2
	cd libxml2 && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --prefix=$(SRCBASE)/opt --host=mips-linux --without-python
	@$(MAKE) -C  libxml2 all
	 cd libxml2 && \
	$(MAKE) install

sqlite/stamp-h2:
	cd sqlite-3.7.3 && \
	touch stamp-h2;

sqlite:sqlite/stamp-h2
	cd sqlite-3.7.3 && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --build=i386-pc-linux-gnu --prefix=$(SRCBASE)/opt --host=mips-linux  --enable-shared --enable-static \
	--disable-readline --disable-tcl --enable-threadsafe
	@$(MAKE) -C sqlite-3.7.3 all 
	cd sqlite-3.7.3 && \
	$(MAKE) install

openssl/stamp-h2:
	cd openssl &&\
	touch stamp-h2;
.PHONY: openssl/stamp-h2

openssl:openssl/stamp-h2
	cd openssl && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(SRCBASE)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		./Configure \
			shared no-zlib \
			-O2   -pipe  -I$(SRCBASE)/opt/include \
			--openssldir=/opt/share/openssl \
			--prefix=/opt \
			--install_prefix=$(SRCBASE) \
			linux-mipsel 
	@$(MAKE) -C openssl \
		AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		AR="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar r" \
		\
		\
		MANDIR=/opt/man \
		EX_LIBS=" -L$(SRCBASE)/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib -ldl" \
		DIRS="crypto ssl apps test"
	 cd openssl && \
	$(MAKE) install
	cp -rf openssl/apps/openssl openssl-ipk-2.1/opt/tmp/bin/
	cp -rf openssl/apps/openssl.cnf openssl-ipk-2.1/opt/tmp/share/openssl/
	cp -rf openssl/libssl.so.1.0.0 openssl-ipk-2.1/opt/tmp/lib/
	cp -rf openssl/libssl.so openssl-ipk-2.1/opt/tmp/lib/
	cp -rf openssl/libcrypto.so.1.0.0 openssl-ipk-2.1/opt/tmp/lib/
	cp -rf openssl/libcrypto.so openssl-ipk-2.1/opt/tmp/lib/                     

nzbget/stamp-h2:
	cd nzbget-0.7.0 \
	touch stamp-h2;

#nzbget:	nzbget/stamp-h2	
#	@$(MAKE) -C nzbget-0.7.0 all
#	$(STRIP) nzbget-0.7.0/dm2_nzbget
#	cp -rf nzbget-0.7.0/dm2_nzbget DownloadMaster-ipk-2.1/opt/tmp/bin/
	
nzbget:  nzbget/stamp-h2
	cd nzbget-0.7.0 && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	LIBPREF=$(LD_DIR) \
	CPPFLAGS="-O2   -pipe  -I$(SRCBASE)/opt/include " \
	LDFLAGS=" -L$(SRCBASE)/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib " \
	./configure --build=i386-pc-linux-gnu --host=mips-linux --disable-parcheck --prefix=$(SRCBASE)/opt --with-libxml2-includes=$(SRCBASE)/libxml2/include --with-openssl-includes=$(SRCBASE)/openssl/include --with-libxml2-libraries=$(SRCBASE)/libxml2/.libs/ --with-openssl-libraries=$(SRCBASE)/openssl
	@$(MAKE) -C nzbget-0.7.0 all
	$(STRIP) nzbget-0.7.0/nzbget
	cp -rf nzbget-0.7.0/nzbget DownloadMaster-ipk-2.1/opt/tmp/bin/dm2_nzbget
	
libevent/stamp-h2:
	cd libevent \
	touch stamp-h2;
libevent:libevent/stamp-h2
	cd libevent && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --build=i386-pc-linux-gnu --host=mipsel-linux --target=mipsel-linux --prefix=$(SRCBASE)/opt
	@$(MAKE) -C libevent all
	 cd libevent && \
	$(MAKE) install

libcurl/stamp-h2:
	cd libcurl \
	touch stamp-h2;
	
libcurl:libcurl/stamp-h2
	cd libcurl && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --build=i386-pc-linux-gnu --host=mipsel-linux --target=mipsel-linux --prefix=$(SRCBASE)/opt --disable-thread --enable-shared --disable-static --enable-ares --enable-cookies --enable-crypto-auth --enable-nonblocking --enable-file --enable-ftp --enable-http --enable-ipv6 --enable-tftp --disable-nls --disable-ares --disable-dict --disable-debug --disable-gopher --disable-ldap --disable-manual --disable-telnet --disable-verbose --with-random=/dev/urandom --with-ssl=$(SRCBASE) --without-gnutls --without-krb4 --without-libidn --with-zlib=$(SRCBASE) --with-ca-bundle=$(SRCBASE)/opt/share/curl/curl-ca-bundle.crt
	@$(MAKE) -C libcurl all
	 cd libcurl && \
	$(MAKE) install
	cp -rf $(SRCBASE)/opt/bin/curl $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/bin/
	#cp -rf $(SRCBASE)/opt/bin/curl-config libcurl-ipk-2.1/opt/tmp/bin/
	cp -rf $(SRCBASE)/opt/lib/libcurl.so $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/lib/
	cp -rf $(SRCBASE)/opt/lib/libcurl.so.4 $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/lib/
	cp -rf $(SRCBASE)/opt/lib/libcurl.so.4.5.0 $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/lib/

transmission-2.92/stamp-h2:
	cd transmission-2.92 \
	touch stamp-h2;
	
transmission-2.92: libpasswd nvram-encrypt zlib libcurl transmission-2.92/stamp-h2
	cd transmission-2.92 && \
	LDFLAGS="-L$(SRCBASE)/opt/lib -lpasswd -I$(SRCBASE)/opt/include -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib -L$(SRCBASE)/opt/lib -lz" \
	AR=mipsel-linux-ar AS=mipsel-linux-as LD=mipsel-linux-ld NM=mipsel-linux-nm CC=mipsel-linux-gcc CPP="mipsel-linux-gcc -E" GCC=mipsel-linux-gcc CXX=mipsel-linux-g++ RANLIB=mipsel-linux-ranlib STRIP=mipsel-linux-strip \
	OPENSSL_CFLAGS='-I$(SRCBASE)/opt/include  ' OPENSSL_LIBS='-Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/../lib -L$(SRCBASE)/opt/lib -lssl -lcrypto -ldl  ' LIBCURL_CFLAGS='-I$(SRCBASE)/opt/include  ' LIBCURL_LIBS='-L$(SRCBASE)/opt/lib -lcurl  ' LIBEVENT_CFLAGS='-I$(SRCBASE)/opt/include ' LIBEVENT_LIBS='-L$(SRCBASE)/opt/lib -levent  ' ZLIB_CFLAGS='-I$(SRCBASE)/opt/include' ZLIB_LIBS='-L$(SRCBASE)/opt/lib -lz ' \
	./configure --without-gtk --host=mipsel-linux --target=mipsel-linux --prefix=/opt --libdir=/opt/lib/
	@$(MAKE) -C transmission-2.92 all
	$(STRIP) transmission-2.92/daemon/transmission-daemon
	cp -rf transmission-2.92/daemon/transmission-daemon DownloadMaster-ipk-2.1/opt/tmp/bin/dm2_transmission-daemon

readline/stamp-h2:
	cd readline \
	touch stamp-h2;
readline:readline/stamp-h2
	cd readline && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --build=i386-pc-linux-gnu --host=mipsel-linux --target=mipsel-linux --prefix=$(SRCBASE)/opt --disable-nls --disable-static --with-curses
	@$(MAKE) -C readline all
	 cd readline && \
	$(MAKE) install
	#$(STRIP) readline/shlib/libreadline.so.6.1 \
	#cp -rf readline/shlib/libreadline.so.6.1 DownloadMaster-ipk-2.1/opt/tmp/lib/libreadline.so.6
expat/stamp-h2:
	cd expat \
	touch stamp-h2;
expat:expat/stamp-h2
	cd expat && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
	./configure --build=i386-pc-linux-gnu --host=mipsel-linux --target=mipsel-linux --disable-static --prefix=$(SRCBASE)/opt --disable-nls
	@$(MAKE) -C expat all
	 cd expat && \
	$(MAKE) install

wxbase/stamp-h2:
	cd wxbase && \
	touch stamp-h2
wxbase: wxbase/stamp-h2
	cd wxbase && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		CPPFLAGS="-O2   -pipe  -I$(SRCBASE)/opt/include " \
		LDFLAGS=" -L$(SRCBASE)/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib " \
		ac_cv_path_SDL_CONFIG=no \
		./configure \
		--prefix=$(SRCBASE)/opt \
		--build=i386-pc-linux-gnu \
		--host=mipsel-linux \
		--target=mipsel-linux \
		--disable-precomp-headers \
		--disable-gui \
		--without-subdirs \
		--with-regex=builtin \
		--with-zlib=sys \
		--with-expat=sys \
		--enable-largefile \
		--without-sdl \
		--disable-sdltest \
		--enable-unicode

	@$(MAKE) -C wxbase all
	 cd wxbase && \
	$(MAKE) install
	#$(STRIP) wxbase/lib/libwx_baseu-2.8.so.0.8.0 
	#$(STRIP) wxbase/lib/libwx_baseu_net-2.8.so.0.8.0 
	#cp -rf wxbase/lib/libwx_baseu-2.8.so.0.8.0 DownloadMaster-ipk-2.1/opt/tmp/lib/libwx_baseu-2.8.so.0
	#cp -rf wxbase/lib/libwx_baseu_net-2.8.so.0.8.0 DownloadMaster-ipk-2.1/opt/tmp/lib/libwx_baseu_net-2.8.so.0

crypto/stamp-h2:
	cd crypto++ && \
	touch stamp-h2

crypto:crypto/stamp-h2
	
	@$(MAKE) -C crypto++ all \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		CXX=$(TOOLCHAIN)/nowrap/mipsel-linux-uclibc-g++ \
		CPPFLAGS="-O2   -pipe  -I$(SRCBASE)/opt/include " \
		LDFLAGS=" -L$(SRCBASE)/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib "
		mkdir -p $(SRCBASE)/opt/include/cryptopp
		chmod -R 777 $(SRCBASE)/opt/include/cryptopp
		cd crypto++ && \
		cp -rf *.h $(SRCBASE)/opt/include/cryptopp &&\
		cp -rf *.a $(SRCBASE)/opt/lib

amule/stamp-h2:
	cd amuled && \
	touch stamp-h2

amule:amule/stamp-h2 wxbase
	cd amuled && \
	AR=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ar AS=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-as LD=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ld NM=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-nm CC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CPP="$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc -E" GCC=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-gcc CXX=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-g++ RANLIB=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-ranlib STRIP=$(TOOLCHAIN)/bin/mipsel-linux-uclibc-strip \
		CPPFLAGS="-O2   -pipe  -I$(SRCBASE)/opt/include " \
		LDFLAGS=" -L$(SRCBASE)/opt/lib -Wl,-rpath,/opt/lib -Wl,-rpath-link,$(SRCBASE)/opt/lib " \
		ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes CXX=$(TOOLCHAIN)/nowrap/mipsel-linux-uclibc-g++ \
		./configure \
		--build=i386-pc-linux-gnu --host=mipsel-linux --target=mipsel-linux --prefix=/opt --disable-debug --enable-optimize --enable-alcc --enable-amule-daemon --enable-webserver --enable-amulecmd --enable-upnp --disable-monolithic --disable-alc --disable-amulecmdgui --disable-cas --disable-wxcas --disable-systray --with-curl-config=$(SRCBASE)/bin/curl-config --with-gdlib-prefix=$(SRCBASE)/opt --with-libpng-prefix=$(SRCBASE)/opt --with-libupnp-prefix=$(SRCBASE)/opt --with-wxbase-config=$(SRCBASE)/opt/bin/wx-config --with-wx-config=$(SRCBASE)/opt/bin/wx-config --with-wx-prefix=$(SRCBASE)/opt --with-crypto-prefix=$(SRCBASE)/opt --with-zlib=$(SRCBASE)/opt --disable-nls --disable-static --disable-webserver
	@$(MAKE) -C amuled HOSTCC=gcc 
	$(STRIP) amuled/src/dm2_amule*
	cp -rf amuled/src/dm2_amuled DownloadMaster-ipk-2.1/opt/tmp/bin/
	cp -rf amuled/src/dm2_amulecmd DownloadMaster-ipk-2.1/opt/tmp/bin/
libpasswd-clean:
	-cd libpasswd &&  make clean
	-rm libpasswd/stamp-h2
libpasswd/stamp-h2:
	cd libpasswd \
	touch stamp-h2;
libpasswd:libpasswd/stamp-h2
	cd libpasswd &&  make install
	#cp -rf libpasswd/libpasswd.so DownloadMaster-ipk-2.1/opt/tmp/lib

nvram-encrypt-clean:
	-cd nvram-encrypt &&  make clean
	-rm nvram-encrypt/stamp-h2
nvram-encrypt/stamp-h2:
	cd nvram-encrypt \
	touch stamp-h2;
nvram-encrypt:nvram-encrypt/stamp-h2
	cd nvram-encrypt &&  make 
	cp -rf nvram-encrypt/spwenc.o transmission-2.92/libtransmission
DownloadMaster-ipk:
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/opt/etc/asus_script/arm_i686_mipsel/* $(SRCBASE)/DownloadMaster-ipk-2.1/opt/etc/asus_script/
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/opt/etc/init.d/S50downloadmaster-mipsel $(SRCBASE)/DownloadMaster-ipk-2.1/opt/etc/init.d/S50downloadmaster
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/CONTROL/control-downloadmaster-mipsel $(SRCBASE)/DownloadMaster-ipk-2.1/CONTROL/control
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/CONTROL/preinst-arm-mipsel $(SRCBASE)/DownloadMaster-ipk-2.1/CONTROL/preinst
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/CONTROL/postinst-arm-mipsel-misbig 	$(SRCBASE)/DownloadMaster-ipk-2.1/CONTROL/postinst
	mipsel-linux-strip DownloadMaster-ipk-2.1/opt/tmp/bin/*
	#mipsel-linux-strip DownloadMaster-ipk-2.1/opt/tmp/lib/*
	@$(IPKG_TOOLS)/ipkg-build DownloadMaster-ipk-2.1 ./

openssl-ipk:
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/CONTROL/control-asusopenssl-mipsel $(SRCBASE)/openssl-ipk-2.1/CONTROL/control
	$(STRIP) openssl-ipk-2.1/opt/tmp/bin/*
	$(STRIP) openssl-ipk-2.1/opt/tmp/lib/*
	@$(IPKG_TOOLS)/ipkg-build openssl-ipk-2.1 ./
libcurl-ipk:
	cp -rf $(SRCBASE)/DownloadMaster-ipk-tmp/CONTROL/control-asuslibcurl-mipsel $(SRCBASE)/libcurl-ipk-2.1/CONTROL/control
	$(STRIP) $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/bin/*
	$(STRIP) $(SRCBASE)/libcurl-ipk-2.1/opt/tmp/lib/*
	@$(IPKG_TOOLS)/ipkg-build libcurl-ipk-2.1 ./

.PHONY: crypto/stamp-h2 CGI2.1/stamp-h2 amule/stamp-h2 wxbase/stamp-h2 expat/stamp-h2 readline/stamp-h2 transmission-2.92/stamp-h2 libcurl/stamp-h2 libevent/stamp-h2
.PHONY: nzbget/stamp-h2 ncurses/stamp-h2 openssl/stamp-h2 sqlite/stamp-h2
